// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Block_proc (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        imgInput1_rows_out_din,
        imgInput1_rows_out_full_n,
        imgInput1_rows_out_write,
        imgInput1_cols_out_din,
        imgInput1_cols_out_full_n,
        imgInput1_cols_out_write,
        imgOutput1_rows_out_din,
        imgOutput1_rows_out_full_n,
        imgOutput1_rows_out_write,
        imgOutput1_cols_out_din,
        imgOutput1_cols_out_full_n,
        imgOutput1_cols_out_write
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output  [11:0] imgInput1_rows_out_din;
input   imgInput1_rows_out_full_n;
output   imgInput1_rows_out_write;
output  [11:0] imgInput1_cols_out_din;
input   imgInput1_cols_out_full_n;
output   imgInput1_cols_out_write;
output  [11:0] imgOutput1_rows_out_din;
input   imgOutput1_rows_out_full_n;
output   imgOutput1_rows_out_write;
output  [11:0] imgOutput1_cols_out_din;
input   imgOutput1_cols_out_full_n;
output   imgOutput1_cols_out_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg imgInput1_rows_out_write;
reg imgInput1_cols_out_write;
reg imgOutput1_rows_out_write;
reg imgOutput1_cols_out_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    imgInput1_rows_out_blk_n;
reg    imgInput1_cols_out_blk_n;
reg    imgOutput1_rows_out_blk_n;
reg    imgOutput1_cols_out_blk_n;
reg    ap_block_state1;
reg   [0:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((ap_start == 1'b0) | (imgOutput1_cols_out_full_n == 1'b0) | (imgOutput1_rows_out_full_n == 1'b0) | (imgInput1_cols_out_full_n == 1'b0) | (imgInput1_rows_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (imgOutput1_cols_out_full_n == 1'b0) | (imgOutput1_rows_out_full_n == 1'b0) | (imgInput1_cols_out_full_n == 1'b0) | (imgInput1_rows_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (imgOutput1_cols_out_full_n == 1'b0) | (imgOutput1_rows_out_full_n == 1'b0) | (imgInput1_cols_out_full_n == 1'b0) | (imgInput1_rows_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        imgInput1_cols_out_blk_n = imgInput1_cols_out_full_n;
    end else begin
        imgInput1_cols_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (imgOutput1_cols_out_full_n == 1'b0) | (imgOutput1_rows_out_full_n == 1'b0) | (imgInput1_cols_out_full_n == 1'b0) | (imgInput1_rows_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        imgInput1_cols_out_write = 1'b1;
    end else begin
        imgInput1_cols_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        imgInput1_rows_out_blk_n = imgInput1_rows_out_full_n;
    end else begin
        imgInput1_rows_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (imgOutput1_cols_out_full_n == 1'b0) | (imgOutput1_rows_out_full_n == 1'b0) | (imgInput1_cols_out_full_n == 1'b0) | (imgInput1_rows_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        imgInput1_rows_out_write = 1'b1;
    end else begin
        imgInput1_rows_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        imgOutput1_cols_out_blk_n = imgOutput1_cols_out_full_n;
    end else begin
        imgOutput1_cols_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (imgOutput1_cols_out_full_n == 1'b0) | (imgOutput1_rows_out_full_n == 1'b0) | (imgInput1_cols_out_full_n == 1'b0) | (imgInput1_rows_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        imgOutput1_cols_out_write = 1'b1;
    end else begin
        imgOutput1_cols_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        imgOutput1_rows_out_blk_n = imgOutput1_rows_out_full_n;
    end else begin
        imgOutput1_rows_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (imgOutput1_cols_out_full_n == 1'b0) | (imgOutput1_rows_out_full_n == 1'b0) | (imgInput1_cols_out_full_n == 1'b0) | (imgInput1_rows_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        imgOutput1_rows_out_write = 1'b1;
    end else begin
        imgOutput1_rows_out_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (imgOutput1_cols_out_full_n == 1'b0) | (imgOutput1_rows_out_full_n == 1'b0) | (imgInput1_cols_out_full_n == 1'b0) | (imgInput1_rows_out_full_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign imgInput1_cols_out_din = 12'd1920;

assign imgInput1_rows_out_din = 12'd1080;

assign imgOutput1_cols_out_din = 12'd1920;

assign imgOutput1_rows_out_din = 12'd1080;

endmodule //Block_proc
