#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("p_src_TDATA", 8, hls_in, 0, "axis", "in_data", 1),
	Port_Property("p_src_TKEEP", 1, hls_in, 1, "axis", "in_data", 1),
	Port_Property("p_src_TSTRB", 1, hls_in, 2, "axis", "in_data", 1),
	Port_Property("p_src_TUSER", 1, hls_in, 3, "axis", "in_data", 1),
	Port_Property("p_src_TLAST", 1, hls_in, 4, "axis", "in_data", 1),
	Port_Property("p_src_TID", 1, hls_in, 5, "axis", "in_data", 1),
	Port_Property("p_src_TDEST", 1, hls_in, 6, "axis", "in_data", 1),
	Port_Property("p_dst_TDATA", 8, hls_out, 7, "axis", "out_data", 1),
	Port_Property("p_dst_TKEEP", 1, hls_out, 8, "axis", "out_data", 1),
	Port_Property("p_dst_TSTRB", 1, hls_out, 9, "axis", "out_data", 1),
	Port_Property("p_dst_TUSER", 1, hls_out, 10, "axis", "out_data", 1),
	Port_Property("p_dst_TLAST", 1, hls_out, 11, "axis", "out_data", 1),
	Port_Property("p_dst_TID", 1, hls_out, 12, "axis", "out_data", 1),
	Port_Property("p_dst_TDEST", 1, hls_out, 13, "axis", "out_data", 1),
	Port_Property("R_address0", 4, hls_out, 14, "ap_memory", "mem_address", 1),
	Port_Property("R_ce0", 1, hls_out, 14, "ap_memory", "mem_ce", 1),
	Port_Property("R_d0", 32, hls_out, 14, "ap_memory", "mem_din", 1),
	Port_Property("R_q0", 32, hls_in, 14, "ap_memory", "mem_dout", 1),
	Port_Property("R_we0", 1, hls_out, 14, "ap_memory", "mem_we", 1),
	Port_Property("R_address1", 4, hls_out, 14, "ap_memory", "mem_address", 1),
	Port_Property("R_ce1", 1, hls_out, 14, "ap_memory", "mem_ce", 1),
	Port_Property("R_d1", 32, hls_out, 14, "ap_memory", "mem_din", 1),
	Port_Property("R_q1", 32, hls_in, 14, "ap_memory", "mem_dout", 1),
	Port_Property("R_we1", 1, hls_out, 14, "ap_memory", "mem_we", 1),
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst_n", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("p_src_TVALID", 1, hls_in, 6, "axis", "in_vld", 1),
	Port_Property("p_src_TREADY", 1, hls_out, 6, "axis", "in_acc", 1),
	Port_Property("p_dst_TVALID", 1, hls_out, 13, "axis", "out_vld", 1),
	Port_Property("p_dst_TREADY", 1, hls_in, 13, "axis", "out_acc", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
};
const char* HLS_Design_Meta::dut_name = "warp_stream_accel";
