# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/ASUS/Desktop/sem 5 project/EagleEye/EagleEye.srcs/sources_1/bd/design_2/ip/design_2_warp_stream_accel_0_0/design_2_warp_stream_accel_0_0.xci
# IP: The module: 'design_2_warp_stream_accel_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ASUS/Desktop/sem 5 project/EagleEye/EagleEye.srcs/sources_1/bd/design_2/ip/design_2_warp_stream_accel_0_0/constraints/warp_stream_accel_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_warp_stream_accel_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/ASUS/Desktop/sem 5 project/EagleEye/EagleEye.srcs/sources_1/bd/design_2/ip/design_2_warp_stream_accel_0_0/design_2_warp_stream_accel_0_0.xci
# IP: The module: 'design_2_warp_stream_accel_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ASUS/Desktop/sem 5 project/EagleEye/EagleEye.srcs/sources_1/bd/design_2/ip/design_2_warp_stream_accel_0_0/constraints/warp_stream_accel_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_warp_stream_accel_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
