// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="warp_stream_accel,hls_ip_2018_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=9.912812,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=116,HLS_SYN_DSP=55,HLS_SYN_FF=13221,HLS_SYN_LUT=23229,HLS_VERSION=2018_3}" *)

module warp_stream_accel (
        p_src_TDATA,
        p_src_TKEEP,
        p_src_TSTRB,
        p_src_TUSER,
        p_src_TLAST,
        p_src_TID,
        p_src_TDEST,
        p_dst_TDATA,
        p_dst_TKEEP,
        p_dst_TSTRB,
        p_dst_TUSER,
        p_dst_TLAST,
        p_dst_TID,
        p_dst_TDEST,
        R_address0,
        R_ce0,
        R_d0,
        R_q0,
        R_we0,
        R_address1,
        R_ce1,
        R_d1,
        R_q1,
        R_we1,
        ap_clk,
        ap_rst_n,
        ap_start,
        p_src_TVALID,
        p_src_TREADY,
        p_dst_TVALID,
        p_dst_TREADY,
        ap_done,
        ap_ready,
        ap_idle
);


input  [7:0] p_src_TDATA;
input  [0:0] p_src_TKEEP;
input  [0:0] p_src_TSTRB;
input  [0:0] p_src_TUSER;
input  [0:0] p_src_TLAST;
input  [0:0] p_src_TID;
input  [0:0] p_src_TDEST;
output  [7:0] p_dst_TDATA;
output  [0:0] p_dst_TKEEP;
output  [0:0] p_dst_TSTRB;
output  [0:0] p_dst_TUSER;
output  [0:0] p_dst_TLAST;
output  [0:0] p_dst_TID;
output  [0:0] p_dst_TDEST;
output  [3:0] R_address0;
output   R_ce0;
output  [31:0] R_d0;
input  [31:0] R_q0;
output   R_we0;
output  [3:0] R_address1;
output   R_ce1;
output  [31:0] R_d1;
input  [31:0] R_q1;
output   R_we1;
input   ap_clk;
input   ap_rst_n;
input   ap_start;
input   p_src_TVALID;
output   p_src_TREADY;
output   p_dst_TVALID;
input   p_dst_TREADY;
output   ap_done;
output   ap_ready;
output   ap_idle;

 reg    ap_rst_n_inv;
wire    Block_proc_U0_ap_start;
wire    Block_proc_U0_ap_done;
wire    Block_proc_U0_ap_continue;
wire    Block_proc_U0_ap_idle;
wire    Block_proc_U0_ap_ready;
wire   [11:0] Block_proc_U0_imgInput1_rows_out_din;
wire    Block_proc_U0_imgInput1_rows_out_write;
wire   [11:0] Block_proc_U0_imgInput1_cols_out_din;
wire    Block_proc_U0_imgInput1_cols_out_write;
wire   [11:0] Block_proc_U0_imgOutput1_rows_out_din;
wire    Block_proc_U0_imgOutput1_rows_out_write;
wire   [11:0] Block_proc_U0_imgOutput1_cols_out_din;
wire    Block_proc_U0_imgOutput1_cols_out_write;
wire    AXIvideo2xfMat_U0_ap_start;
wire    AXIvideo2xfMat_U0_ap_done;
wire    AXIvideo2xfMat_U0_ap_continue;
wire    AXIvideo2xfMat_U0_ap_idle;
wire    AXIvideo2xfMat_U0_ap_ready;
wire    AXIvideo2xfMat_U0_p_src_TREADY;
wire    AXIvideo2xfMat_U0_img_rows_read;
wire    AXIvideo2xfMat_U0_img_cols_read;
wire   [7:0] AXIvideo2xfMat_U0_img_data_V_din;
wire    AXIvideo2xfMat_U0_img_data_V_write;
wire   [11:0] AXIvideo2xfMat_U0_img_rows_out_din;
wire    AXIvideo2xfMat_U0_img_rows_out_write;
wire   [11:0] AXIvideo2xfMat_U0_img_cols_out_din;
wire    AXIvideo2xfMat_U0_img_cols_out_write;
wire    warpTransform_U0_ap_start;
wire    warpTransform_U0_start_out;
wire    warpTransform_U0_start_write;
wire    warpTransform_U0_p_src_mat_rows_read;
wire    warpTransform_U0_p_src_mat_cols_read;
wire    warpTransform_U0_p_src_mat_data_V_read;
wire    warpTransform_U0_p_dst_mat_rows_read;
wire    warpTransform_U0_p_dst_mat_cols_read;
wire   [7:0] warpTransform_U0_p_dst_mat_data_V_din;
wire    warpTransform_U0_p_dst_mat_data_V_write;
wire   [3:0] warpTransform_U0_P_matrix_address0;
wire    warpTransform_U0_P_matrix_ce0;
wire   [31:0] warpTransform_U0_P_matrix_d0;
wire    warpTransform_U0_P_matrix_we0;
wire   [3:0] warpTransform_U0_P_matrix_address1;
wire    warpTransform_U0_P_matrix_ce1;
wire   [31:0] warpTransform_U0_P_matrix_d1;
wire    warpTransform_U0_P_matrix_we1;
wire   [11:0] warpTransform_U0_p_dst_mat_rows_out_din;
wire    warpTransform_U0_p_dst_mat_rows_out_write;
wire   [11:0] warpTransform_U0_p_dst_mat_cols_out_din;
wire    warpTransform_U0_p_dst_mat_cols_out_write;
wire    warpTransform_U0_ap_done;
wire    warpTransform_U0_ap_ready;
wire    warpTransform_U0_ap_idle;
wire    warpTransform_U0_ap_continue;
wire    xfMat2AXIvideo_U0_ap_start;
wire    xfMat2AXIvideo_U0_ap_done;
wire    xfMat2AXIvideo_U0_ap_continue;
wire    xfMat2AXIvideo_U0_ap_idle;
wire    xfMat2AXIvideo_U0_ap_ready;
wire    xfMat2AXIvideo_U0_img_rows_read;
wire    xfMat2AXIvideo_U0_img_cols_read;
wire    xfMat2AXIvideo_U0_img_data_V_read;
wire   [7:0] xfMat2AXIvideo_U0_p_dst_TDATA;
wire    xfMat2AXIvideo_U0_p_dst_TVALID;
wire   [0:0] xfMat2AXIvideo_U0_p_dst_TKEEP;
wire   [0:0] xfMat2AXIvideo_U0_p_dst_TSTRB;
wire   [0:0] xfMat2AXIvideo_U0_p_dst_TUSER;
wire   [0:0] xfMat2AXIvideo_U0_p_dst_TLAST;
wire   [0:0] xfMat2AXIvideo_U0_p_dst_TID;
wire   [0:0] xfMat2AXIvideo_U0_p_dst_TDEST;
wire    ap_sync_continue;
wire    imgInput1_rows_c_full_n;
wire   [11:0] imgInput1_rows_c_dout;
wire    imgInput1_rows_c_empty_n;
wire    imgInput1_cols_c_full_n;
wire   [11:0] imgInput1_cols_c_dout;
wire    imgInput1_cols_c_empty_n;
wire    imgOutput1_rows_c_full_n;
wire   [11:0] imgOutput1_rows_c_dout;
wire    imgOutput1_rows_c_empty_n;
wire    imgOutput1_cols_c_full_n;
wire   [11:0] imgOutput1_cols_c_dout;
wire    imgOutput1_cols_c_empty_n;
wire    imgInput1_data_V_full_n;
wire   [7:0] imgInput1_data_V_dout;
wire    imgInput1_data_V_empty_n;
wire    imgInput1_rows_c4_full_n;
wire   [11:0] imgInput1_rows_c4_dout;
wire    imgInput1_rows_c4_empty_n;
wire    imgInput1_cols_c5_full_n;
wire   [11:0] imgInput1_cols_c5_dout;
wire    imgInput1_cols_c5_empty_n;
wire    imgOutput1_data_V_full_n;
wire   [7:0] imgOutput1_data_V_dout;
wire    imgOutput1_data_V_empty_n;
wire    imgOutput1_rows_c6_full_n;
wire   [11:0] imgOutput1_rows_c6_dout;
wire    imgOutput1_rows_c6_empty_n;
wire    imgOutput1_cols_c7_full_n;
wire   [11:0] imgOutput1_cols_c7_dout;
wire    imgOutput1_cols_c7_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
reg    ap_sync_reg_Block_proc_U0_ap_ready;
wire    ap_sync_Block_proc_U0_ap_ready;
reg   [1:0] Block_proc_U0_ap_ready_count;
reg    ap_sync_reg_AXIvideo2xfMat_U0_ap_ready;
wire    ap_sync_AXIvideo2xfMat_U0_ap_ready;
reg   [1:0] AXIvideo2xfMat_U0_ap_ready_count;
reg    ap_sync_reg_warpTransform_U0_ap_ready;
wire    ap_sync_warpTransform_U0_ap_ready;
reg   [1:0] warpTransform_U0_ap_ready_count;
wire    Block_proc_U0_start_full_n;
wire    Block_proc_U0_start_write;
wire    AXIvideo2xfMat_U0_start_full_n;
wire    AXIvideo2xfMat_U0_start_write;
wire   [0:0] start_for_xfMat2AXIvideo_U0_din;
wire    start_for_xfMat2AXIvideo_U0_full_n;
wire   [0:0] start_for_xfMat2AXIvideo_U0_dout;
wire    start_for_xfMat2AXIvideo_U0_empty_n;
wire    xfMat2AXIvideo_U0_start_full_n;
wire    xfMat2AXIvideo_U0_start_write;

// power-on initialization
initial begin
#0 ap_sync_reg_Block_proc_U0_ap_ready = 1'b0;
#0 Block_proc_U0_ap_ready_count = 2'd0;
#0 ap_sync_reg_AXIvideo2xfMat_U0_ap_ready = 1'b0;
#0 AXIvideo2xfMat_U0_ap_ready_count = 2'd0;
#0 ap_sync_reg_warpTransform_U0_ap_ready = 1'b0;
#0 warpTransform_U0_ap_ready_count = 2'd0;
end

Block_proc Block_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Block_proc_U0_ap_start),
    .ap_done(Block_proc_U0_ap_done),
    .ap_continue(Block_proc_U0_ap_continue),
    .ap_idle(Block_proc_U0_ap_idle),
    .ap_ready(Block_proc_U0_ap_ready),
    .imgInput1_rows_out_din(Block_proc_U0_imgInput1_rows_out_din),
    .imgInput1_rows_out_full_n(imgInput1_rows_c_full_n),
    .imgInput1_rows_out_write(Block_proc_U0_imgInput1_rows_out_write),
    .imgInput1_cols_out_din(Block_proc_U0_imgInput1_cols_out_din),
    .imgInput1_cols_out_full_n(imgInput1_cols_c_full_n),
    .imgInput1_cols_out_write(Block_proc_U0_imgInput1_cols_out_write),
    .imgOutput1_rows_out_din(Block_proc_U0_imgOutput1_rows_out_din),
    .imgOutput1_rows_out_full_n(imgOutput1_rows_c_full_n),
    .imgOutput1_rows_out_write(Block_proc_U0_imgOutput1_rows_out_write),
    .imgOutput1_cols_out_din(Block_proc_U0_imgOutput1_cols_out_din),
    .imgOutput1_cols_out_full_n(imgOutput1_cols_c_full_n),
    .imgOutput1_cols_out_write(Block_proc_U0_imgOutput1_cols_out_write)
);

AXIvideo2xfMat AXIvideo2xfMat_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(AXIvideo2xfMat_U0_ap_start),
    .ap_done(AXIvideo2xfMat_U0_ap_done),
    .ap_continue(AXIvideo2xfMat_U0_ap_continue),
    .ap_idle(AXIvideo2xfMat_U0_ap_idle),
    .ap_ready(AXIvideo2xfMat_U0_ap_ready),
    .p_src_TDATA(p_src_TDATA),
    .p_src_TVALID(p_src_TVALID),
    .p_src_TREADY(AXIvideo2xfMat_U0_p_src_TREADY),
    .p_src_TKEEP(p_src_TKEEP),
    .p_src_TSTRB(p_src_TSTRB),
    .p_src_TUSER(p_src_TUSER),
    .p_src_TLAST(p_src_TLAST),
    .p_src_TID(p_src_TID),
    .p_src_TDEST(p_src_TDEST),
    .img_rows_dout(imgInput1_rows_c_dout),
    .img_rows_empty_n(imgInput1_rows_c_empty_n),
    .img_rows_read(AXIvideo2xfMat_U0_img_rows_read),
    .img_cols_dout(imgInput1_cols_c_dout),
    .img_cols_empty_n(imgInput1_cols_c_empty_n),
    .img_cols_read(AXIvideo2xfMat_U0_img_cols_read),
    .img_data_V_din(AXIvideo2xfMat_U0_img_data_V_din),
    .img_data_V_full_n(imgInput1_data_V_full_n),
    .img_data_V_write(AXIvideo2xfMat_U0_img_data_V_write),
    .img_rows_out_din(AXIvideo2xfMat_U0_img_rows_out_din),
    .img_rows_out_full_n(imgInput1_rows_c4_full_n),
    .img_rows_out_write(AXIvideo2xfMat_U0_img_rows_out_write),
    .img_cols_out_din(AXIvideo2xfMat_U0_img_cols_out_din),
    .img_cols_out_full_n(imgInput1_cols_c5_full_n),
    .img_cols_out_write(AXIvideo2xfMat_U0_img_cols_out_write)
);

warpTransform warpTransform_U0(
    .ap_start(warpTransform_U0_ap_start),
    .start_full_n(start_for_xfMat2AXIvideo_U0_full_n),
    .start_out(warpTransform_U0_start_out),
    .start_write(warpTransform_U0_start_write),
    .p_src_mat_rows_dout(imgInput1_rows_c4_dout),
    .p_src_mat_rows_empty_n(imgInput1_rows_c4_empty_n),
    .p_src_mat_rows_read(warpTransform_U0_p_src_mat_rows_read),
    .p_src_mat_cols_dout(imgInput1_cols_c5_dout),
    .p_src_mat_cols_empty_n(imgInput1_cols_c5_empty_n),
    .p_src_mat_cols_read(warpTransform_U0_p_src_mat_cols_read),
    .p_src_mat_data_V_dout(imgInput1_data_V_dout),
    .p_src_mat_data_V_empty_n(imgInput1_data_V_empty_n),
    .p_src_mat_data_V_read(warpTransform_U0_p_src_mat_data_V_read),
    .p_dst_mat_rows_dout(imgOutput1_rows_c_dout),
    .p_dst_mat_rows_empty_n(imgOutput1_rows_c_empty_n),
    .p_dst_mat_rows_read(warpTransform_U0_p_dst_mat_rows_read),
    .p_dst_mat_cols_dout(imgOutput1_cols_c_dout),
    .p_dst_mat_cols_empty_n(imgOutput1_cols_c_empty_n),
    .p_dst_mat_cols_read(warpTransform_U0_p_dst_mat_cols_read),
    .p_dst_mat_data_V_din(warpTransform_U0_p_dst_mat_data_V_din),
    .p_dst_mat_data_V_full_n(imgOutput1_data_V_full_n),
    .p_dst_mat_data_V_write(warpTransform_U0_p_dst_mat_data_V_write),
    .P_matrix_address0(warpTransform_U0_P_matrix_address0),
    .P_matrix_ce0(warpTransform_U0_P_matrix_ce0),
    .P_matrix_d0(warpTransform_U0_P_matrix_d0),
    .P_matrix_q0(R_q0),
    .P_matrix_we0(warpTransform_U0_P_matrix_we0),
    .P_matrix_address1(warpTransform_U0_P_matrix_address1),
    .P_matrix_ce1(warpTransform_U0_P_matrix_ce1),
    .P_matrix_d1(warpTransform_U0_P_matrix_d1),
    .P_matrix_q1(32'd0),
    .P_matrix_we1(warpTransform_U0_P_matrix_we1),
    .p_dst_mat_rows_out_din(warpTransform_U0_p_dst_mat_rows_out_din),
    .p_dst_mat_rows_out_full_n(imgOutput1_rows_c6_full_n),
    .p_dst_mat_rows_out_write(warpTransform_U0_p_dst_mat_rows_out_write),
    .p_dst_mat_cols_out_din(warpTransform_U0_p_dst_mat_cols_out_din),
    .p_dst_mat_cols_out_full_n(imgOutput1_cols_c7_full_n),
    .p_dst_mat_cols_out_write(warpTransform_U0_p_dst_mat_cols_out_write),
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_done(warpTransform_U0_ap_done),
    .ap_ready(warpTransform_U0_ap_ready),
    .ap_idle(warpTransform_U0_ap_idle),
    .ap_continue(warpTransform_U0_ap_continue)
);

xfMat2AXIvideo xfMat2AXIvideo_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(xfMat2AXIvideo_U0_ap_start),
    .ap_done(xfMat2AXIvideo_U0_ap_done),
    .ap_continue(xfMat2AXIvideo_U0_ap_continue),
    .ap_idle(xfMat2AXIvideo_U0_ap_idle),
    .ap_ready(xfMat2AXIvideo_U0_ap_ready),
    .img_rows_dout(imgOutput1_rows_c6_dout),
    .img_rows_empty_n(imgOutput1_rows_c6_empty_n),
    .img_rows_read(xfMat2AXIvideo_U0_img_rows_read),
    .img_cols_dout(imgOutput1_cols_c7_dout),
    .img_cols_empty_n(imgOutput1_cols_c7_empty_n),
    .img_cols_read(xfMat2AXIvideo_U0_img_cols_read),
    .img_data_V_dout(imgOutput1_data_V_dout),
    .img_data_V_empty_n(imgOutput1_data_V_empty_n),
    .img_data_V_read(xfMat2AXIvideo_U0_img_data_V_read),
    .p_dst_TDATA(xfMat2AXIvideo_U0_p_dst_TDATA),
    .p_dst_TVALID(xfMat2AXIvideo_U0_p_dst_TVALID),
    .p_dst_TREADY(p_dst_TREADY),
    .p_dst_TKEEP(xfMat2AXIvideo_U0_p_dst_TKEEP),
    .p_dst_TSTRB(xfMat2AXIvideo_U0_p_dst_TSTRB),
    .p_dst_TUSER(xfMat2AXIvideo_U0_p_dst_TUSER),
    .p_dst_TLAST(xfMat2AXIvideo_U0_p_dst_TLAST),
    .p_dst_TID(xfMat2AXIvideo_U0_p_dst_TID),
    .p_dst_TDEST(xfMat2AXIvideo_U0_p_dst_TDEST)
);

fifo_w12_d2_A_x imgInput1_rows_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_proc_U0_imgInput1_rows_out_din),
    .if_full_n(imgInput1_rows_c_full_n),
    .if_write(Block_proc_U0_imgInput1_rows_out_write),
    .if_dout(imgInput1_rows_c_dout),
    .if_empty_n(imgInput1_rows_c_empty_n),
    .if_read(AXIvideo2xfMat_U0_img_rows_read)
);

fifo_w12_d2_A_x imgInput1_cols_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_proc_U0_imgInput1_cols_out_din),
    .if_full_n(imgInput1_cols_c_full_n),
    .if_write(Block_proc_U0_imgInput1_cols_out_write),
    .if_dout(imgInput1_cols_c_dout),
    .if_empty_n(imgInput1_cols_c_empty_n),
    .if_read(AXIvideo2xfMat_U0_img_cols_read)
);

fifo_w12_d3_A imgOutput1_rows_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_proc_U0_imgOutput1_rows_out_din),
    .if_full_n(imgOutput1_rows_c_full_n),
    .if_write(Block_proc_U0_imgOutput1_rows_out_write),
    .if_dout(imgOutput1_rows_c_dout),
    .if_empty_n(imgOutput1_rows_c_empty_n),
    .if_read(warpTransform_U0_p_dst_mat_rows_read)
);

fifo_w12_d3_A imgOutput1_cols_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_proc_U0_imgOutput1_cols_out_din),
    .if_full_n(imgOutput1_cols_c_full_n),
    .if_write(Block_proc_U0_imgOutput1_cols_out_write),
    .if_dout(imgOutput1_cols_c_dout),
    .if_empty_n(imgOutput1_cols_c_empty_n),
    .if_read(warpTransform_U0_p_dst_mat_cols_read)
);

fifo_w8_d1_A imgInput1_data_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2xfMat_U0_img_data_V_din),
    .if_full_n(imgInput1_data_V_full_n),
    .if_write(AXIvideo2xfMat_U0_img_data_V_write),
    .if_dout(imgInput1_data_V_dout),
    .if_empty_n(imgInput1_data_V_empty_n),
    .if_read(warpTransform_U0_p_src_mat_data_V_read)
);

fifo_w12_d2_A_x imgInput1_rows_c4_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2xfMat_U0_img_rows_out_din),
    .if_full_n(imgInput1_rows_c4_full_n),
    .if_write(AXIvideo2xfMat_U0_img_rows_out_write),
    .if_dout(imgInput1_rows_c4_dout),
    .if_empty_n(imgInput1_rows_c4_empty_n),
    .if_read(warpTransform_U0_p_src_mat_rows_read)
);

fifo_w12_d2_A_x imgInput1_cols_c5_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2xfMat_U0_img_cols_out_din),
    .if_full_n(imgInput1_cols_c5_full_n),
    .if_write(AXIvideo2xfMat_U0_img_cols_out_write),
    .if_dout(imgInput1_cols_c5_dout),
    .if_empty_n(imgInput1_cols_c5_empty_n),
    .if_read(warpTransform_U0_p_src_mat_cols_read)
);

fifo_w8_d1_A imgOutput1_data_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(warpTransform_U0_p_dst_mat_data_V_din),
    .if_full_n(imgOutput1_data_V_full_n),
    .if_write(warpTransform_U0_p_dst_mat_data_V_write),
    .if_dout(imgOutput1_data_V_dout),
    .if_empty_n(imgOutput1_data_V_empty_n),
    .if_read(xfMat2AXIvideo_U0_img_data_V_read)
);

fifo_w12_d2_A_x imgOutput1_rows_c6_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(warpTransform_U0_p_dst_mat_rows_out_din),
    .if_full_n(imgOutput1_rows_c6_full_n),
    .if_write(warpTransform_U0_p_dst_mat_rows_out_write),
    .if_dout(imgOutput1_rows_c6_dout),
    .if_empty_n(imgOutput1_rows_c6_empty_n),
    .if_read(xfMat2AXIvideo_U0_img_rows_read)
);

fifo_w12_d2_A_x imgOutput1_cols_c7_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(warpTransform_U0_p_dst_mat_cols_out_din),
    .if_full_n(imgOutput1_cols_c7_full_n),
    .if_write(warpTransform_U0_p_dst_mat_cols_out_write),
    .if_dout(imgOutput1_cols_c7_dout),
    .if_empty_n(imgOutput1_cols_c7_empty_n),
    .if_read(xfMat2AXIvideo_U0_img_cols_read)
);

start_for_xfMat2Ab3s start_for_xfMat2Ab3s_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_xfMat2AXIvideo_U0_din),
    .if_full_n(start_for_xfMat2AXIvideo_U0_full_n),
    .if_write(warpTransform_U0_start_write),
    .if_dout(start_for_xfMat2AXIvideo_U0_dout),
    .if_empty_n(start_for_xfMat2AXIvideo_U0_empty_n),
    .if_read(xfMat2AXIvideo_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_AXIvideo2xfMat_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_AXIvideo2xfMat_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_AXIvideo2xfMat_U0_ap_ready <= ap_sync_AXIvideo2xfMat_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_Block_proc_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_Block_proc_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_Block_proc_U0_ap_ready <= ap_sync_Block_proc_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_warpTransform_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_warpTransform_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_warpTransform_U0_ap_ready <= ap_sync_warpTransform_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_sync_ready == 1'b1) & (1'b0 == AXIvideo2xfMat_U0_ap_ready))) begin
        AXIvideo2xfMat_U0_ap_ready_count <= (AXIvideo2xfMat_U0_ap_ready_count - 2'd1);
    end else if (((1'b1 == AXIvideo2xfMat_U0_ap_ready) & (ap_sync_ready == 1'b0))) begin
        AXIvideo2xfMat_U0_ap_ready_count <= (AXIvideo2xfMat_U0_ap_ready_count + 2'd1);
    end
end

always @ (posedge ap_clk) begin
    if (((ap_sync_ready == 1'b1) & (1'b0 == Block_proc_U0_ap_ready))) begin
        Block_proc_U0_ap_ready_count <= (Block_proc_U0_ap_ready_count - 2'd1);
    end else if (((1'b1 == Block_proc_U0_ap_ready) & (ap_sync_ready == 1'b0))) begin
        Block_proc_U0_ap_ready_count <= (Block_proc_U0_ap_ready_count + 2'd1);
    end
end

always @ (posedge ap_clk) begin
    if (((ap_sync_ready == 1'b1) & (warpTransform_U0_ap_ready == 1'b0))) begin
        warpTransform_U0_ap_ready_count <= (warpTransform_U0_ap_ready_count - 2'd1);
    end else if (((warpTransform_U0_ap_ready == 1'b1) & (ap_sync_ready == 1'b0))) begin
        warpTransform_U0_ap_ready_count <= (warpTransform_U0_ap_ready_count + 2'd1);
    end
end

assign AXIvideo2xfMat_U0_ap_continue = 1'b1;

assign AXIvideo2xfMat_U0_ap_start = ((ap_sync_reg_AXIvideo2xfMat_U0_ap_ready ^ 1'b1) & ap_start);

assign AXIvideo2xfMat_U0_start_full_n = 1'b1;

assign AXIvideo2xfMat_U0_start_write = 1'b0;

assign Block_proc_U0_ap_continue = 1'b1;

assign Block_proc_U0_ap_start = ((ap_sync_reg_Block_proc_U0_ap_ready ^ 1'b1) & ap_start);

assign Block_proc_U0_start_full_n = 1'b1;

assign Block_proc_U0_start_write = 1'b0;

assign R_address0 = warpTransform_U0_P_matrix_address0;

assign R_address1 = 4'd0;

assign R_ce0 = warpTransform_U0_P_matrix_ce0;

assign R_ce1 = 1'b0;

assign R_d0 = 32'd0;

assign R_d1 = 32'd0;

assign R_we0 = 1'b0;

assign R_we1 = 1'b0;

assign ap_done = xfMat2AXIvideo_U0_ap_done;

assign ap_idle = (xfMat2AXIvideo_U0_ap_idle & warpTransform_U0_ap_idle & Block_proc_U0_ap_idle & AXIvideo2xfMat_U0_ap_idle);

assign ap_ready = ap_sync_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_AXIvideo2xfMat_U0_ap_ready = (ap_sync_reg_AXIvideo2xfMat_U0_ap_ready | AXIvideo2xfMat_U0_ap_ready);

assign ap_sync_Block_proc_U0_ap_ready = (ap_sync_reg_Block_proc_U0_ap_ready | Block_proc_U0_ap_ready);

assign ap_sync_continue = 1'b1;

assign ap_sync_done = xfMat2AXIvideo_U0_ap_done;

assign ap_sync_ready = (ap_sync_warpTransform_U0_ap_ready & ap_sync_Block_proc_U0_ap_ready & ap_sync_AXIvideo2xfMat_U0_ap_ready);

assign ap_sync_warpTransform_U0_ap_ready = (warpTransform_U0_ap_ready | ap_sync_reg_warpTransform_U0_ap_ready);

assign p_dst_TDATA = xfMat2AXIvideo_U0_p_dst_TDATA;

assign p_dst_TDEST = xfMat2AXIvideo_U0_p_dst_TDEST;

assign p_dst_TID = xfMat2AXIvideo_U0_p_dst_TID;

assign p_dst_TKEEP = xfMat2AXIvideo_U0_p_dst_TKEEP;

assign p_dst_TLAST = xfMat2AXIvideo_U0_p_dst_TLAST;

assign p_dst_TSTRB = xfMat2AXIvideo_U0_p_dst_TSTRB;

assign p_dst_TUSER = xfMat2AXIvideo_U0_p_dst_TUSER;

assign p_dst_TVALID = xfMat2AXIvideo_U0_p_dst_TVALID;

assign p_src_TREADY = AXIvideo2xfMat_U0_p_src_TREADY;

assign start_for_xfMat2AXIvideo_U0_din = 1'b1;

assign warpTransform_U0_ap_continue = 1'b1;

assign warpTransform_U0_ap_start = ((ap_sync_reg_warpTransform_U0_ap_ready ^ 1'b1) & ap_start);

assign xfMat2AXIvideo_U0_ap_continue = 1'b1;

assign xfMat2AXIvideo_U0_ap_start = start_for_xfMat2AXIvideo_U0_empty_n;

assign xfMat2AXIvideo_U0_start_full_n = 1'b1;

assign xfMat2AXIvideo_U0_start_write = 1'b0;

endmodule //warp_stream_accel
