// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "AXIvideo2xfMat.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic AXIvideo2xfMat::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic AXIvideo2xfMat::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<8> AXIvideo2xfMat::ap_ST_fsm_state1 = "1";
const sc_lv<8> AXIvideo2xfMat::ap_ST_fsm_state2 = "10";
const sc_lv<8> AXIvideo2xfMat::ap_ST_fsm_state3 = "100";
const sc_lv<8> AXIvideo2xfMat::ap_ST_fsm_state4 = "1000";
const sc_lv<8> AXIvideo2xfMat::ap_ST_fsm_pp1_stage0 = "10000";
const sc_lv<8> AXIvideo2xfMat::ap_ST_fsm_state7 = "100000";
const sc_lv<8> AXIvideo2xfMat::ap_ST_fsm_state8 = "1000000";
const sc_lv<8> AXIvideo2xfMat::ap_ST_fsm_state9 = "10000000";
const sc_lv<32> AXIvideo2xfMat::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool AXIvideo2xfMat::ap_const_boolean_1 = true;
const sc_lv<1> AXIvideo2xfMat::ap_const_lv1_0 = "0";
const sc_lv<1> AXIvideo2xfMat::ap_const_lv1_1 = "1";
const sc_lv<2> AXIvideo2xfMat::ap_const_lv2_0 = "00";
const sc_lv<2> AXIvideo2xfMat::ap_const_lv2_2 = "10";
const sc_lv<2> AXIvideo2xfMat::ap_const_lv2_3 = "11";
const sc_lv<2> AXIvideo2xfMat::ap_const_lv2_1 = "1";
const sc_lv<32> AXIvideo2xfMat::ap_const_lv32_1 = "1";
const sc_lv<32> AXIvideo2xfMat::ap_const_lv32_4 = "100";
const bool AXIvideo2xfMat::ap_const_boolean_0 = false;
const sc_lv<32> AXIvideo2xfMat::ap_const_lv32_6 = "110";
const sc_lv<32> AXIvideo2xfMat::ap_const_lv32_3 = "11";
const sc_lv<32> AXIvideo2xfMat::ap_const_lv32_7 = "111";
const sc_lv<32> AXIvideo2xfMat::ap_const_lv32_2 = "10";
const sc_lv<11> AXIvideo2xfMat::ap_const_lv11_0 = "00000000000";
const sc_lv<32> AXIvideo2xfMat::ap_const_lv32_5 = "101";
const sc_lv<11> AXIvideo2xfMat::ap_const_lv11_1 = "1";

AXIvideo2xfMat::AXIvideo2xfMat(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_AXI_video_strm_V_data_V_0_ack_in);
    sensitive << ( AXI_video_strm_V_data_V_0_state );

    SC_METHOD(thread_AXI_video_strm_V_data_V_0_ack_out);
    sensitive << ( AXI_video_strm_V_data_V_0_vld_out );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_predicate_op65_read_state5 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( eol_2_i_reg_319 );

    SC_METHOD(thread_AXI_video_strm_V_data_V_0_data_out);
    sensitive << ( AXI_video_strm_V_data_V_0_payload_A );
    sensitive << ( AXI_video_strm_V_data_V_0_payload_B );
    sensitive << ( AXI_video_strm_V_data_V_0_sel );

    SC_METHOD(thread_AXI_video_strm_V_data_V_0_load_A);
    sensitive << ( AXI_video_strm_V_data_V_0_sel_wr );
    sensitive << ( AXI_video_strm_V_data_V_0_state_cmp_full );

    SC_METHOD(thread_AXI_video_strm_V_data_V_0_load_B);
    sensitive << ( AXI_video_strm_V_data_V_0_sel_wr );
    sensitive << ( AXI_video_strm_V_data_V_0_state_cmp_full );

    SC_METHOD(thread_AXI_video_strm_V_data_V_0_sel);
    sensitive << ( AXI_video_strm_V_data_V_0_sel_rd );

    SC_METHOD(thread_AXI_video_strm_V_data_V_0_state_cmp_full);
    sensitive << ( AXI_video_strm_V_data_V_0_state );

    SC_METHOD(thread_AXI_video_strm_V_data_V_0_vld_in);
    sensitive << ( p_src_TVALID );

    SC_METHOD(thread_AXI_video_strm_V_data_V_0_vld_out);
    sensitive << ( AXI_video_strm_V_data_V_0_state );

    SC_METHOD(thread_AXI_video_strm_V_dest_V_0_ack_out);
    sensitive << ( AXI_video_strm_V_data_V_0_vld_out );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_predicate_op65_read_state5 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( eol_2_i_reg_319 );

    SC_METHOD(thread_AXI_video_strm_V_dest_V_0_vld_in);
    sensitive << ( p_src_TVALID );

    SC_METHOD(thread_AXI_video_strm_V_last_V_0_ack_in);
    sensitive << ( AXI_video_strm_V_last_V_0_state );

    SC_METHOD(thread_AXI_video_strm_V_last_V_0_ack_out);
    sensitive << ( AXI_video_strm_V_data_V_0_vld_out );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_predicate_op65_read_state5 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( eol_2_i_reg_319 );

    SC_METHOD(thread_AXI_video_strm_V_last_V_0_data_out);
    sensitive << ( AXI_video_strm_V_last_V_0_payload_A );
    sensitive << ( AXI_video_strm_V_last_V_0_payload_B );
    sensitive << ( AXI_video_strm_V_last_V_0_sel );

    SC_METHOD(thread_AXI_video_strm_V_last_V_0_load_A);
    sensitive << ( AXI_video_strm_V_last_V_0_sel_wr );
    sensitive << ( AXI_video_strm_V_last_V_0_state_cmp_full );

    SC_METHOD(thread_AXI_video_strm_V_last_V_0_load_B);
    sensitive << ( AXI_video_strm_V_last_V_0_sel_wr );
    sensitive << ( AXI_video_strm_V_last_V_0_state_cmp_full );

    SC_METHOD(thread_AXI_video_strm_V_last_V_0_sel);
    sensitive << ( AXI_video_strm_V_last_V_0_sel_rd );

    SC_METHOD(thread_AXI_video_strm_V_last_V_0_state_cmp_full);
    sensitive << ( AXI_video_strm_V_last_V_0_state );

    SC_METHOD(thread_AXI_video_strm_V_last_V_0_vld_in);
    sensitive << ( p_src_TVALID );

    SC_METHOD(thread_AXI_video_strm_V_last_V_0_vld_out);
    sensitive << ( AXI_video_strm_V_last_V_0_state );

    SC_METHOD(thread_AXI_video_strm_V_user_V_0_ack_in);
    sensitive << ( AXI_video_strm_V_user_V_0_state );

    SC_METHOD(thread_AXI_video_strm_V_user_V_0_ack_out);
    sensitive << ( AXI_video_strm_V_data_V_0_vld_out );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_predicate_op65_read_state5 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( eol_2_i_reg_319 );

    SC_METHOD(thread_AXI_video_strm_V_user_V_0_data_out);
    sensitive << ( AXI_video_strm_V_user_V_0_payload_A );
    sensitive << ( AXI_video_strm_V_user_V_0_payload_B );
    sensitive << ( AXI_video_strm_V_user_V_0_sel );

    SC_METHOD(thread_AXI_video_strm_V_user_V_0_load_A);
    sensitive << ( AXI_video_strm_V_user_V_0_sel_wr );
    sensitive << ( AXI_video_strm_V_user_V_0_state_cmp_full );

    SC_METHOD(thread_AXI_video_strm_V_user_V_0_load_B);
    sensitive << ( AXI_video_strm_V_user_V_0_sel_wr );
    sensitive << ( AXI_video_strm_V_user_V_0_state_cmp_full );

    SC_METHOD(thread_AXI_video_strm_V_user_V_0_sel);
    sensitive << ( AXI_video_strm_V_user_V_0_sel_rd );

    SC_METHOD(thread_AXI_video_strm_V_user_V_0_state_cmp_full);
    sensitive << ( AXI_video_strm_V_user_V_0_state );

    SC_METHOD(thread_AXI_video_strm_V_user_V_0_vld_in);
    sensitive << ( p_src_TVALID );

    SC_METHOD(thread_AXI_video_strm_V_user_V_0_vld_out);
    sensitive << ( AXI_video_strm_V_user_V_0_state );

    SC_METHOD(thread_ap_CS_fsm_pp1_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp1_stage0);

    SC_METHOD(thread_ap_block_pp1_stage0_01001);
    sensitive << ( AXI_video_strm_V_data_V_0_vld_out );
    sensitive << ( img_data_V_full_n );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( tmp_138_i_reg_431 );
    sensitive << ( ap_predicate_op65_read_state5 );

    SC_METHOD(thread_ap_block_pp1_stage0_11001);
    sensitive << ( AXI_video_strm_V_data_V_0_vld_out );
    sensitive << ( img_data_V_full_n );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( tmp_138_i_reg_431 );
    sensitive << ( ap_predicate_op65_read_state5 );

    SC_METHOD(thread_ap_block_pp1_stage0_subdone);
    sensitive << ( AXI_video_strm_V_data_V_0_vld_out );
    sensitive << ( img_data_V_full_n );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( tmp_138_i_reg_431 );
    sensitive << ( ap_predicate_op65_read_state5 );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( img_rows_empty_n );
    sensitive << ( img_cols_empty_n );
    sensitive << ( img_rows_out_full_n );
    sensitive << ( img_cols_out_full_n );

    SC_METHOD(thread_ap_block_state5_pp1_stage0_iter0);
    sensitive << ( AXI_video_strm_V_data_V_0_vld_out );
    sensitive << ( ap_predicate_op65_read_state5 );

    SC_METHOD(thread_ap_block_state6_pp1_stage0_iter1);
    sensitive << ( img_data_V_full_n );
    sensitive << ( tmp_138_i_reg_431 );

    SC_METHOD(thread_ap_block_state8);
    sensitive << ( AXI_video_strm_V_data_V_0_vld_out );
    sensitive << ( eol_2_i_reg_319 );

    SC_METHOD(thread_ap_condition_568);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_block_pp1_stage0_11001 );

    SC_METHOD(thread_ap_condition_pp1_exit_iter0_state5);
    sensitive << ( tmp_138_i_fu_367_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( tmp_137_i_fu_352_p2 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_ap_enable_pp1);
    sensitive << ( ap_idle_pp1 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp1);
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );

    SC_METHOD(thread_ap_phi_mux_axi_data_V_1_i_phi_fu_238_p4);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( tmp_138_i_reg_431 );
    sensitive << ( axi_data_V_1_i_reg_235 );
    sensitive << ( p_Val2_s_reg_282 );

    SC_METHOD(thread_ap_phi_mux_eol_2_i_phi_fu_322_p4);
    sensitive << ( eol_2_i_reg_319 );

    SC_METHOD(thread_ap_phi_mux_eol_i_phi_fu_250_p4);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( tmp_138_i_reg_431 );
    sensitive << ( eol_i_reg_246 );
    sensitive << ( axi_last_V_2_i_reg_269 );

    SC_METHOD(thread_ap_phi_mux_eol_phi_fu_227_p4);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( tmp_138_i_reg_431 );
    sensitive << ( eol_reg_224 );
    sensitive << ( axi_last_V_2_i_reg_269 );

    SC_METHOD(thread_ap_phi_reg_pp1_iter0_axi_last_V_2_i_reg_269);

    SC_METHOD(thread_ap_phi_reg_pp1_iter0_p_Val2_s_reg_282);

    SC_METHOD(thread_ap_predicate_op65_read_state5);
    sensitive << ( tmp_138_i_fu_367_p2 );
    sensitive << ( brmerge_i_fu_381_p2 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( tmp_137_i_fu_352_p2 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_brmerge_i_fu_381_p2);
    sensitive << ( ap_phi_mux_eol_i_phi_fu_250_p4 );
    sensitive << ( sof_1_i_fu_136 );

    SC_METHOD(thread_i_cast_cast_i_fu_348_p1);
    sensitive << ( i_i_reg_213 );

    SC_METHOD(thread_i_fu_357_p2);
    sensitive << ( i_i_reg_213 );

    SC_METHOD(thread_img_cols_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( img_cols_empty_n );

    SC_METHOD(thread_img_cols_out_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( img_cols_out_full_n );

    SC_METHOD(thread_img_cols_out_din);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( img_rows_empty_n );
    sensitive << ( img_cols_dout );
    sensitive << ( img_cols_empty_n );
    sensitive << ( img_rows_out_full_n );
    sensitive << ( img_cols_out_full_n );

    SC_METHOD(thread_img_cols_out_write);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( img_rows_empty_n );
    sensitive << ( img_cols_empty_n );
    sensitive << ( img_rows_out_full_n );
    sensitive << ( img_cols_out_full_n );

    SC_METHOD(thread_img_cols_read);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( img_rows_empty_n );
    sensitive << ( img_cols_empty_n );
    sensitive << ( img_rows_out_full_n );
    sensitive << ( img_cols_out_full_n );

    SC_METHOD(thread_img_data_V_blk_n);
    sensitive << ( img_data_V_full_n );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( tmp_138_i_reg_431 );

    SC_METHOD(thread_img_data_V_din);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( tmp_138_i_reg_431 );
    sensitive << ( p_Val2_s_reg_282 );
    sensitive << ( ap_block_pp1_stage0_01001 );

    SC_METHOD(thread_img_data_V_write);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( tmp_138_i_reg_431 );
    sensitive << ( ap_block_pp1_stage0_11001 );

    SC_METHOD(thread_img_rows_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( img_rows_empty_n );

    SC_METHOD(thread_img_rows_out_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( img_rows_out_full_n );

    SC_METHOD(thread_img_rows_out_din);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( img_rows_dout );
    sensitive << ( img_rows_empty_n );
    sensitive << ( img_cols_empty_n );
    sensitive << ( img_rows_out_full_n );
    sensitive << ( img_cols_out_full_n );

    SC_METHOD(thread_img_rows_out_write);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( img_rows_empty_n );
    sensitive << ( img_cols_empty_n );
    sensitive << ( img_rows_out_full_n );
    sensitive << ( img_cols_out_full_n );

    SC_METHOD(thread_img_rows_read);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( img_rows_empty_n );
    sensitive << ( img_cols_empty_n );
    sensitive << ( img_rows_out_full_n );
    sensitive << ( img_cols_out_full_n );

    SC_METHOD(thread_j_cast_cast_i_fu_363_p1);
    sensitive << ( j_i_reg_258 );

    SC_METHOD(thread_j_fu_372_p2);
    sensitive << ( j_i_reg_258 );

    SC_METHOD(thread_p_src_TDATA_blk_n);
    sensitive << ( AXI_video_strm_V_data_V_0_state );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( tmp_138_i_fu_367_p2 );
    sensitive << ( brmerge_i_fu_381_p2 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( eol_2_i_reg_319 );

    SC_METHOD(thread_p_src_TREADY);
    sensitive << ( AXI_video_strm_V_dest_V_0_state );

    SC_METHOD(thread_tmp_137_i_fu_352_p2);
    sensitive << ( img_rows_read_reg_392 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( i_cast_cast_i_fu_348_p1 );

    SC_METHOD(thread_tmp_138_i_fu_367_p2);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( img_cols_read_reg_397 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( j_cast_cast_i_fu_363_p1 );

    SC_METHOD(thread_tmp_user_V_fu_339_p1);
    sensitive << ( AXI_video_strm_V_user_V_0_data_out );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( AXI_video_strm_V_data_V_0_vld_out );
    sensitive << ( img_rows_empty_n );
    sensitive << ( img_cols_empty_n );
    sensitive << ( img_rows_out_full_n );
    sensitive << ( img_cols_out_full_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( tmp_138_i_fu_367_p2 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_phi_mux_eol_2_i_phi_fu_322_p4 );
    sensitive << ( tmp_137_i_fu_352_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_block_pp1_stage0_subdone );
    sensitive << ( eol_2_i_reg_319 );
    sensitive << ( tmp_user_V_fu_339_p1 );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "00000001";
    AXI_video_strm_V_data_V_0_sel_rd = SC_LOGIC_0;
    AXI_video_strm_V_data_V_0_sel_wr = SC_LOGIC_0;
    AXI_video_strm_V_data_V_0_state = "00";
    AXI_video_strm_V_user_V_0_sel_rd = SC_LOGIC_0;
    AXI_video_strm_V_user_V_0_sel_wr = SC_LOGIC_0;
    AXI_video_strm_V_user_V_0_state = "00";
    AXI_video_strm_V_last_V_0_sel_rd = SC_LOGIC_0;
    AXI_video_strm_V_last_V_0_sel_wr = SC_LOGIC_0;
    AXI_video_strm_V_last_V_0_state = "00";
    AXI_video_strm_V_dest_V_0_state = "00";
    ap_enable_reg_pp1_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp1_iter1 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "AXIvideo2xfMat_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, p_src_TDATA, "(port)p_src_TDATA");
    sc_trace(mVcdFile, p_src_TVALID, "(port)p_src_TVALID");
    sc_trace(mVcdFile, p_src_TREADY, "(port)p_src_TREADY");
    sc_trace(mVcdFile, p_src_TKEEP, "(port)p_src_TKEEP");
    sc_trace(mVcdFile, p_src_TSTRB, "(port)p_src_TSTRB");
    sc_trace(mVcdFile, p_src_TUSER, "(port)p_src_TUSER");
    sc_trace(mVcdFile, p_src_TLAST, "(port)p_src_TLAST");
    sc_trace(mVcdFile, p_src_TID, "(port)p_src_TID");
    sc_trace(mVcdFile, p_src_TDEST, "(port)p_src_TDEST");
    sc_trace(mVcdFile, img_rows_dout, "(port)img_rows_dout");
    sc_trace(mVcdFile, img_rows_empty_n, "(port)img_rows_empty_n");
    sc_trace(mVcdFile, img_rows_read, "(port)img_rows_read");
    sc_trace(mVcdFile, img_cols_dout, "(port)img_cols_dout");
    sc_trace(mVcdFile, img_cols_empty_n, "(port)img_cols_empty_n");
    sc_trace(mVcdFile, img_cols_read, "(port)img_cols_read");
    sc_trace(mVcdFile, img_data_V_din, "(port)img_data_V_din");
    sc_trace(mVcdFile, img_data_V_full_n, "(port)img_data_V_full_n");
    sc_trace(mVcdFile, img_data_V_write, "(port)img_data_V_write");
    sc_trace(mVcdFile, img_rows_out_din, "(port)img_rows_out_din");
    sc_trace(mVcdFile, img_rows_out_full_n, "(port)img_rows_out_full_n");
    sc_trace(mVcdFile, img_rows_out_write, "(port)img_rows_out_write");
    sc_trace(mVcdFile, img_cols_out_din, "(port)img_cols_out_din");
    sc_trace(mVcdFile, img_cols_out_full_n, "(port)img_cols_out_full_n");
    sc_trace(mVcdFile, img_cols_out_write, "(port)img_cols_out_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, AXI_video_strm_V_data_V_0_data_out, "AXI_video_strm_V_data_V_0_data_out");
    sc_trace(mVcdFile, AXI_video_strm_V_data_V_0_vld_in, "AXI_video_strm_V_data_V_0_vld_in");
    sc_trace(mVcdFile, AXI_video_strm_V_data_V_0_vld_out, "AXI_video_strm_V_data_V_0_vld_out");
    sc_trace(mVcdFile, AXI_video_strm_V_data_V_0_ack_in, "AXI_video_strm_V_data_V_0_ack_in");
    sc_trace(mVcdFile, AXI_video_strm_V_data_V_0_ack_out, "AXI_video_strm_V_data_V_0_ack_out");
    sc_trace(mVcdFile, AXI_video_strm_V_data_V_0_payload_A, "AXI_video_strm_V_data_V_0_payload_A");
    sc_trace(mVcdFile, AXI_video_strm_V_data_V_0_payload_B, "AXI_video_strm_V_data_V_0_payload_B");
    sc_trace(mVcdFile, AXI_video_strm_V_data_V_0_sel_rd, "AXI_video_strm_V_data_V_0_sel_rd");
    sc_trace(mVcdFile, AXI_video_strm_V_data_V_0_sel_wr, "AXI_video_strm_V_data_V_0_sel_wr");
    sc_trace(mVcdFile, AXI_video_strm_V_data_V_0_sel, "AXI_video_strm_V_data_V_0_sel");
    sc_trace(mVcdFile, AXI_video_strm_V_data_V_0_load_A, "AXI_video_strm_V_data_V_0_load_A");
    sc_trace(mVcdFile, AXI_video_strm_V_data_V_0_load_B, "AXI_video_strm_V_data_V_0_load_B");
    sc_trace(mVcdFile, AXI_video_strm_V_data_V_0_state, "AXI_video_strm_V_data_V_0_state");
    sc_trace(mVcdFile, AXI_video_strm_V_data_V_0_state_cmp_full, "AXI_video_strm_V_data_V_0_state_cmp_full");
    sc_trace(mVcdFile, AXI_video_strm_V_user_V_0_data_out, "AXI_video_strm_V_user_V_0_data_out");
    sc_trace(mVcdFile, AXI_video_strm_V_user_V_0_vld_in, "AXI_video_strm_V_user_V_0_vld_in");
    sc_trace(mVcdFile, AXI_video_strm_V_user_V_0_vld_out, "AXI_video_strm_V_user_V_0_vld_out");
    sc_trace(mVcdFile, AXI_video_strm_V_user_V_0_ack_in, "AXI_video_strm_V_user_V_0_ack_in");
    sc_trace(mVcdFile, AXI_video_strm_V_user_V_0_ack_out, "AXI_video_strm_V_user_V_0_ack_out");
    sc_trace(mVcdFile, AXI_video_strm_V_user_V_0_payload_A, "AXI_video_strm_V_user_V_0_payload_A");
    sc_trace(mVcdFile, AXI_video_strm_V_user_V_0_payload_B, "AXI_video_strm_V_user_V_0_payload_B");
    sc_trace(mVcdFile, AXI_video_strm_V_user_V_0_sel_rd, "AXI_video_strm_V_user_V_0_sel_rd");
    sc_trace(mVcdFile, AXI_video_strm_V_user_V_0_sel_wr, "AXI_video_strm_V_user_V_0_sel_wr");
    sc_trace(mVcdFile, AXI_video_strm_V_user_V_0_sel, "AXI_video_strm_V_user_V_0_sel");
    sc_trace(mVcdFile, AXI_video_strm_V_user_V_0_load_A, "AXI_video_strm_V_user_V_0_load_A");
    sc_trace(mVcdFile, AXI_video_strm_V_user_V_0_load_B, "AXI_video_strm_V_user_V_0_load_B");
    sc_trace(mVcdFile, AXI_video_strm_V_user_V_0_state, "AXI_video_strm_V_user_V_0_state");
    sc_trace(mVcdFile, AXI_video_strm_V_user_V_0_state_cmp_full, "AXI_video_strm_V_user_V_0_state_cmp_full");
    sc_trace(mVcdFile, AXI_video_strm_V_last_V_0_data_out, "AXI_video_strm_V_last_V_0_data_out");
    sc_trace(mVcdFile, AXI_video_strm_V_last_V_0_vld_in, "AXI_video_strm_V_last_V_0_vld_in");
    sc_trace(mVcdFile, AXI_video_strm_V_last_V_0_vld_out, "AXI_video_strm_V_last_V_0_vld_out");
    sc_trace(mVcdFile, AXI_video_strm_V_last_V_0_ack_in, "AXI_video_strm_V_last_V_0_ack_in");
    sc_trace(mVcdFile, AXI_video_strm_V_last_V_0_ack_out, "AXI_video_strm_V_last_V_0_ack_out");
    sc_trace(mVcdFile, AXI_video_strm_V_last_V_0_payload_A, "AXI_video_strm_V_last_V_0_payload_A");
    sc_trace(mVcdFile, AXI_video_strm_V_last_V_0_payload_B, "AXI_video_strm_V_last_V_0_payload_B");
    sc_trace(mVcdFile, AXI_video_strm_V_last_V_0_sel_rd, "AXI_video_strm_V_last_V_0_sel_rd");
    sc_trace(mVcdFile, AXI_video_strm_V_last_V_0_sel_wr, "AXI_video_strm_V_last_V_0_sel_wr");
    sc_trace(mVcdFile, AXI_video_strm_V_last_V_0_sel, "AXI_video_strm_V_last_V_0_sel");
    sc_trace(mVcdFile, AXI_video_strm_V_last_V_0_load_A, "AXI_video_strm_V_last_V_0_load_A");
    sc_trace(mVcdFile, AXI_video_strm_V_last_V_0_load_B, "AXI_video_strm_V_last_V_0_load_B");
    sc_trace(mVcdFile, AXI_video_strm_V_last_V_0_state, "AXI_video_strm_V_last_V_0_state");
    sc_trace(mVcdFile, AXI_video_strm_V_last_V_0_state_cmp_full, "AXI_video_strm_V_last_V_0_state_cmp_full");
    sc_trace(mVcdFile, AXI_video_strm_V_dest_V_0_vld_in, "AXI_video_strm_V_dest_V_0_vld_in");
    sc_trace(mVcdFile, AXI_video_strm_V_dest_V_0_ack_out, "AXI_video_strm_V_dest_V_0_ack_out");
    sc_trace(mVcdFile, AXI_video_strm_V_dest_V_0_state, "AXI_video_strm_V_dest_V_0_state");
    sc_trace(mVcdFile, p_src_TDATA_blk_n, "p_src_TDATA_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, ap_CS_fsm_pp1_stage0, "ap_CS_fsm_pp1_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp1_iter0, "ap_enable_reg_pp1_iter0");
    sc_trace(mVcdFile, ap_block_pp1_stage0, "ap_block_pp1_stage0");
    sc_trace(mVcdFile, tmp_138_i_fu_367_p2, "tmp_138_i_fu_367_p2");
    sc_trace(mVcdFile, brmerge_i_fu_381_p2, "brmerge_i_fu_381_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, ap_phi_mux_eol_2_i_phi_fu_322_p4, "ap_phi_mux_eol_2_i_phi_fu_322_p4");
    sc_trace(mVcdFile, img_rows_blk_n, "img_rows_blk_n");
    sc_trace(mVcdFile, img_cols_blk_n, "img_cols_blk_n");
    sc_trace(mVcdFile, img_data_V_blk_n, "img_data_V_blk_n");
    sc_trace(mVcdFile, ap_enable_reg_pp1_iter1, "ap_enable_reg_pp1_iter1");
    sc_trace(mVcdFile, tmp_138_i_reg_431, "tmp_138_i_reg_431");
    sc_trace(mVcdFile, img_rows_out_blk_n, "img_rows_out_blk_n");
    sc_trace(mVcdFile, img_cols_out_blk_n, "img_cols_out_blk_n");
    sc_trace(mVcdFile, eol_reg_224, "eol_reg_224");
    sc_trace(mVcdFile, axi_data_V_1_i_reg_235, "axi_data_V_1_i_reg_235");
    sc_trace(mVcdFile, eol_i_reg_246, "eol_i_reg_246");
    sc_trace(mVcdFile, j_i_reg_258, "j_i_reg_258");
    sc_trace(mVcdFile, axi_last_V_2_i_reg_269, "axi_last_V_2_i_reg_269");
    sc_trace(mVcdFile, p_Val2_s_reg_282, "p_Val2_s_reg_282");
    sc_trace(mVcdFile, img_rows_read_reg_392, "img_rows_read_reg_392");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, img_cols_read_reg_397, "img_cols_read_reg_397");
    sc_trace(mVcdFile, tmp_data_V_reg_402, "tmp_data_V_reg_402");
    sc_trace(mVcdFile, tmp_last_V_reg_410, "tmp_last_V_reg_410");
    sc_trace(mVcdFile, tmp_137_i_fu_352_p2, "tmp_137_i_fu_352_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, i_fu_357_p2, "i_fu_357_p2");
    sc_trace(mVcdFile, i_reg_426, "i_reg_426");
    sc_trace(mVcdFile, ap_predicate_op65_read_state5, "ap_predicate_op65_read_state5");
    sc_trace(mVcdFile, ap_block_state5_pp1_stage0_iter0, "ap_block_state5_pp1_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state6_pp1_stage0_iter1, "ap_block_state6_pp1_stage0_iter1");
    sc_trace(mVcdFile, ap_block_pp1_stage0_11001, "ap_block_pp1_stage0_11001");
    sc_trace(mVcdFile, j_fu_372_p2, "j_fu_372_p2");
    sc_trace(mVcdFile, ap_block_state8, "ap_block_state8");
    sc_trace(mVcdFile, ap_block_pp1_stage0_subdone, "ap_block_pp1_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp1_exit_iter0_state5, "ap_condition_pp1_exit_iter0_state5");
    sc_trace(mVcdFile, axi_last_V_3_i_reg_295, "axi_last_V_3_i_reg_295");
    sc_trace(mVcdFile, axi_last_V1_i_reg_193, "axi_last_V1_i_reg_193");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, axi_data_V_3_i_reg_307, "axi_data_V_3_i_reg_307");
    sc_trace(mVcdFile, axi_data_V1_i_reg_203, "axi_data_V1_i_reg_203");
    sc_trace(mVcdFile, i_i_reg_213, "i_i_reg_213");
    sc_trace(mVcdFile, ap_phi_mux_eol_phi_fu_227_p4, "ap_phi_mux_eol_phi_fu_227_p4");
    sc_trace(mVcdFile, ap_phi_mux_axi_data_V_1_i_phi_fu_238_p4, "ap_phi_mux_axi_data_V_1_i_phi_fu_238_p4");
    sc_trace(mVcdFile, ap_phi_mux_eol_i_phi_fu_250_p4, "ap_phi_mux_eol_i_phi_fu_250_p4");
    sc_trace(mVcdFile, ap_phi_reg_pp1_iter0_axi_last_V_2_i_reg_269, "ap_phi_reg_pp1_iter0_axi_last_V_2_i_reg_269");
    sc_trace(mVcdFile, ap_phi_reg_pp1_iter0_p_Val2_s_reg_282, "ap_phi_reg_pp1_iter0_p_Val2_s_reg_282");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, eol_2_i_reg_319, "eol_2_i_reg_319");
    sc_trace(mVcdFile, ap_block_pp1_stage0_01001, "ap_block_pp1_stage0_01001");
    sc_trace(mVcdFile, sof_1_i_fu_136, "sof_1_i_fu_136");
    sc_trace(mVcdFile, i_cast_cast_i_fu_348_p1, "i_cast_cast_i_fu_348_p1");
    sc_trace(mVcdFile, j_cast_cast_i_fu_363_p1, "j_cast_cast_i_fu_363_p1");
    sc_trace(mVcdFile, tmp_user_V_fu_339_p1, "tmp_user_V_fu_339_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp1, "ap_idle_pp1");
    sc_trace(mVcdFile, ap_enable_pp1, "ap_enable_pp1");
    sc_trace(mVcdFile, ap_condition_568, "ap_condition_568");
#endif

    }
}

AXIvideo2xfMat::~AXIvideo2xfMat() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void AXIvideo2xfMat::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        AXI_video_strm_V_data_V_0_sel_rd = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_data_V_0_ack_out.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_data_V_0_vld_out.read()))) {
            AXI_video_strm_V_data_V_0_sel_rd =  (sc_logic) (~AXI_video_strm_V_data_V_0_sel_rd.read());
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        AXI_video_strm_V_data_V_0_sel_wr = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_data_V_0_vld_in.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_data_V_0_ack_in.read()))) {
            AXI_video_strm_V_data_V_0_sel_wr =  (sc_logic) (~AXI_video_strm_V_data_V_0_sel_wr.read());
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        AXI_video_strm_V_data_V_0_state = ap_const_lv2_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_data_V_0_vld_in.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_data_V_0_ack_out.read()) && 
              esl_seteq<1,2,2>(AXI_video_strm_V_data_V_0_state.read(), ap_const_lv2_3)) || 
             (esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_data_V_0_vld_in.read()) && 
              esl_seteq<1,2,2>(AXI_video_strm_V_data_V_0_state.read(), ap_const_lv2_2)))) {
            AXI_video_strm_V_data_V_0_state = ap_const_lv2_2;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_data_V_0_vld_in.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_data_V_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(AXI_video_strm_V_data_V_0_state.read(), ap_const_lv2_3)) || 
                    (esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_data_V_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(AXI_video_strm_V_data_V_0_state.read(), ap_const_lv2_1)))) {
            AXI_video_strm_V_data_V_0_state = ap_const_lv2_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_data_V_0_vld_in.read()) && 
                     esl_seteq<1,2,2>(AXI_video_strm_V_data_V_0_state.read(), ap_const_lv2_2)) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_data_V_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(AXI_video_strm_V_data_V_0_state.read(), ap_const_lv2_1)) || 
                    (esl_seteq<1,2,2>(AXI_video_strm_V_data_V_0_state.read(), ap_const_lv2_3) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_data_V_0_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_data_V_0_ack_out.read())) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_data_V_0_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_data_V_0_ack_out.read()))))) {
            AXI_video_strm_V_data_V_0_state = ap_const_lv2_3;
        } else {
            AXI_video_strm_V_data_V_0_state = ap_const_lv2_2;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        AXI_video_strm_V_dest_V_0_state = ap_const_lv2_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_dest_V_0_vld_in.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_dest_V_0_ack_out.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_3, AXI_video_strm_V_dest_V_0_state.read())) || 
             (esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_dest_V_0_vld_in.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_2, AXI_video_strm_V_dest_V_0_state.read())))) {
            AXI_video_strm_V_dest_V_0_state = ap_const_lv2_2;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_dest_V_0_vld_in.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_dest_V_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_3, AXI_video_strm_V_dest_V_0_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_dest_V_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, AXI_video_strm_V_dest_V_0_state.read())))) {
            AXI_video_strm_V_dest_V_0_state = ap_const_lv2_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_dest_V_0_vld_in.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_2, AXI_video_strm_V_dest_V_0_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_dest_V_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, AXI_video_strm_V_dest_V_0_state.read())) || 
                    (esl_seteq<1,2,2>(ap_const_lv2_3, AXI_video_strm_V_dest_V_0_state.read()) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_dest_V_0_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_dest_V_0_ack_out.read())) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_dest_V_0_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_dest_V_0_ack_out.read()))))) {
            AXI_video_strm_V_dest_V_0_state = ap_const_lv2_3;
        } else {
            AXI_video_strm_V_dest_V_0_state = ap_const_lv2_2;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        AXI_video_strm_V_last_V_0_sel_rd = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_last_V_0_ack_out.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_last_V_0_vld_out.read()))) {
            AXI_video_strm_V_last_V_0_sel_rd =  (sc_logic) (~AXI_video_strm_V_last_V_0_sel_rd.read());
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        AXI_video_strm_V_last_V_0_sel_wr = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_last_V_0_vld_in.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_last_V_0_ack_in.read()))) {
            AXI_video_strm_V_last_V_0_sel_wr =  (sc_logic) (~AXI_video_strm_V_last_V_0_sel_wr.read());
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        AXI_video_strm_V_last_V_0_state = ap_const_lv2_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_last_V_0_vld_in.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_last_V_0_ack_out.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_3, AXI_video_strm_V_last_V_0_state.read())) || 
             (esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_last_V_0_vld_in.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_2, AXI_video_strm_V_last_V_0_state.read())))) {
            AXI_video_strm_V_last_V_0_state = ap_const_lv2_2;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_last_V_0_vld_in.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_last_V_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_3, AXI_video_strm_V_last_V_0_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_last_V_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, AXI_video_strm_V_last_V_0_state.read())))) {
            AXI_video_strm_V_last_V_0_state = ap_const_lv2_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_last_V_0_vld_in.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_2, AXI_video_strm_V_last_V_0_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_last_V_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, AXI_video_strm_V_last_V_0_state.read())) || 
                    (esl_seteq<1,2,2>(ap_const_lv2_3, AXI_video_strm_V_last_V_0_state.read()) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_last_V_0_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_last_V_0_ack_out.read())) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_last_V_0_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_last_V_0_ack_out.read()))))) {
            AXI_video_strm_V_last_V_0_state = ap_const_lv2_3;
        } else {
            AXI_video_strm_V_last_V_0_state = ap_const_lv2_2;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        AXI_video_strm_V_user_V_0_sel_rd = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_user_V_0_ack_out.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_user_V_0_vld_out.read()))) {
            AXI_video_strm_V_user_V_0_sel_rd =  (sc_logic) (~AXI_video_strm_V_user_V_0_sel_rd.read());
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        AXI_video_strm_V_user_V_0_sel_wr = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_user_V_0_vld_in.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_user_V_0_ack_in.read()))) {
            AXI_video_strm_V_user_V_0_sel_wr =  (sc_logic) (~AXI_video_strm_V_user_V_0_sel_wr.read());
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        AXI_video_strm_V_user_V_0_state = ap_const_lv2_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_user_V_0_vld_in.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_user_V_0_ack_out.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_3, AXI_video_strm_V_user_V_0_state.read())) || 
             (esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_user_V_0_vld_in.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_2, AXI_video_strm_V_user_V_0_state.read())))) {
            AXI_video_strm_V_user_V_0_state = ap_const_lv2_2;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_user_V_0_vld_in.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_user_V_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_3, AXI_video_strm_V_user_V_0_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_user_V_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, AXI_video_strm_V_user_V_0_state.read())))) {
            AXI_video_strm_V_user_V_0_state = ap_const_lv2_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_user_V_0_vld_in.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_2, AXI_video_strm_V_user_V_0_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_user_V_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, AXI_video_strm_V_user_V_0_state.read())) || 
                    (esl_seteq<1,2,2>(ap_const_lv2_3, AXI_video_strm_V_user_V_0_state.read()) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_user_V_0_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_user_V_0_ack_out.read())) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_user_V_0_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_user_V_0_ack_out.read()))))) {
            AXI_video_strm_V_user_V_0_state = ap_const_lv2_3;
        } else {
            AXI_video_strm_V_user_V_0_state = ap_const_lv2_2;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, tmp_137_i_fu_352_p2.read()))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp1_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp1_exit_iter0_state5.read()))) {
            ap_enable_reg_pp1_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_1, tmp_137_i_fu_352_p2.read()))) {
            ap_enable_reg_pp1_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp1_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp1_exit_iter0_state5.read()))) {
            ap_enable_reg_pp1_iter1 = (ap_condition_pp1_exit_iter0_state5.read() ^ ap_const_logic_1);
        } else if (esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp1_iter1 = ap_enable_reg_pp1_iter0.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_1, tmp_137_i_fu_352_p2.read()))) {
            ap_enable_reg_pp1_iter1 = ap_const_logic_0;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        axi_data_V1_i_reg_203 = tmp_data_V_reg_402.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        axi_data_V1_i_reg_203 = axi_data_V_3_i_reg_307.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, tmp_138_i_reg_431.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0))) {
        axi_data_V_1_i_reg_235 = p_Val2_s_reg_282.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, tmp_137_i_fu_352_p2.read()))) {
        axi_data_V_1_i_reg_235 = axi_data_V1_i_reg_203.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        axi_data_V_3_i_reg_307 = axi_data_V_1_i_reg_235.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_i_reg_319.read()) && 
                !(esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_i_reg_319.read()) && esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_data_V_0_vld_out.read())))) {
        axi_data_V_3_i_reg_307 = AXI_video_strm_V_data_V_0_data_out.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        axi_last_V1_i_reg_193 = tmp_last_V_reg_410.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        axi_last_V1_i_reg_193 = axi_last_V_3_i_reg_295.read();
    }
    if (esl_seteq<1,1,1>(ap_condition_568.read(), ap_const_boolean_1)) {
        if ((esl_seteq<1,1,1>(ap_const_lv1_1, tmp_138_i_fu_367_p2.read()) && 
             esl_seteq<1,1,1>(ap_const_lv1_1, brmerge_i_fu_381_p2.read()))) {
            axi_last_V_2_i_reg_269 = ap_phi_mux_eol_phi_fu_227_p4.read();
        } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, tmp_138_i_fu_367_p2.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, brmerge_i_fu_381_p2.read()))) {
            axi_last_V_2_i_reg_269 = AXI_video_strm_V_last_V_0_data_out.read();
        } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
            axi_last_V_2_i_reg_269 = ap_phi_reg_pp1_iter0_axi_last_V_2_i_reg_269.read();
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        axi_last_V_3_i_reg_295 = eol_reg_224.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_i_reg_319.read()) && 
                !(esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_i_reg_319.read()) && esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_data_V_0_vld_out.read())))) {
        axi_last_V_3_i_reg_295 = AXI_video_strm_V_last_V_0_data_out.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        eol_2_i_reg_319 = eol_i_reg_246.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_i_reg_319.read()) && 
                !(esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_i_reg_319.read()) && esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_data_V_0_vld_out.read())))) {
        eol_2_i_reg_319 = AXI_video_strm_V_last_V_0_data_out.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, tmp_138_i_reg_431.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0))) {
        eol_i_reg_246 = axi_last_V_2_i_reg_269.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, tmp_137_i_fu_352_p2.read()))) {
        eol_i_reg_246 = ap_const_lv1_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, tmp_138_i_reg_431.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0))) {
        eol_reg_224 = axi_last_V_2_i_reg_269.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, tmp_137_i_fu_352_p2.read()))) {
        eol_reg_224 = axi_last_V1_i_reg_193.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        i_i_reg_213 = ap_const_lv11_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        i_i_reg_213 = i_reg_426.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, tmp_138_i_fu_367_p2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0))) {
        j_i_reg_258 = j_fu_372_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, tmp_137_i_fu_352_p2.read()))) {
        j_i_reg_258 = ap_const_lv11_0;
    }
    if (esl_seteq<1,1,1>(ap_condition_568.read(), ap_const_boolean_1)) {
        if ((esl_seteq<1,1,1>(ap_const_lv1_1, tmp_138_i_fu_367_p2.read()) && 
             esl_seteq<1,1,1>(ap_const_lv1_1, brmerge_i_fu_381_p2.read()))) {
            p_Val2_s_reg_282 = ap_phi_mux_axi_data_V_1_i_phi_fu_238_p4.read();
        } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, tmp_138_i_fu_367_p2.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, brmerge_i_fu_381_p2.read()))) {
            p_Val2_s_reg_282 = AXI_video_strm_V_data_V_0_data_out.read();
        } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
            p_Val2_s_reg_282 = ap_phi_reg_pp1_iter0_p_Val2_s_reg_282.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, tmp_138_i_fu_367_p2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0))) {
        sof_1_i_fu_136 = ap_const_lv1_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        sof_1_i_fu_136 = ap_const_lv1_1;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_data_V_0_load_A.read())) {
        AXI_video_strm_V_data_V_0_payload_A = p_src_TDATA.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_data_V_0_load_B.read())) {
        AXI_video_strm_V_data_V_0_payload_B = p_src_TDATA.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_last_V_0_load_A.read())) {
        AXI_video_strm_V_last_V_0_payload_A = p_src_TLAST.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_last_V_0_load_B.read())) {
        AXI_video_strm_V_last_V_0_payload_B = p_src_TLAST.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_user_V_0_load_A.read())) {
        AXI_video_strm_V_user_V_0_payload_A = p_src_TUSER.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_user_V_0_load_B.read())) {
        AXI_video_strm_V_user_V_0_payload_B = p_src_TUSER.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        i_reg_426 = i_fu_357_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, img_rows_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_cols_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_rows_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_cols_out_full_n.read())))) {
        img_cols_read_reg_397 = img_cols_dout.read();
        img_rows_read_reg_392 = img_rows_dout.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0))) {
        tmp_138_i_reg_431 = tmp_138_i_fu_367_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(AXI_video_strm_V_data_V_0_vld_out.read(), ap_const_logic_1))) {
        tmp_data_V_reg_402 = AXI_video_strm_V_data_V_0_data_out.read();
        tmp_last_V_reg_410 = AXI_video_strm_V_last_V_0_data_out.read();
    }
}

void AXIvideo2xfMat::thread_AXI_video_strm_V_data_V_0_ack_in() {
    AXI_video_strm_V_data_V_0_ack_in = AXI_video_strm_V_data_V_0_state.read()[1];
}

void AXIvideo2xfMat::thread_AXI_video_strm_V_data_V_0_ack_out() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(AXI_video_strm_V_data_V_0_vld_out.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_i_reg_319.read()) && 
          !(esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_i_reg_319.read()) && esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_data_V_0_vld_out.read()))) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && 
          esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op65_read_state5.read()) && 
          esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0)))) {
        AXI_video_strm_V_data_V_0_ack_out = ap_const_logic_1;
    } else {
        AXI_video_strm_V_data_V_0_ack_out = ap_const_logic_0;
    }
}

void AXIvideo2xfMat::thread_AXI_video_strm_V_data_V_0_data_out() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_data_V_0_sel.read())) {
        AXI_video_strm_V_data_V_0_data_out = AXI_video_strm_V_data_V_0_payload_B.read();
    } else {
        AXI_video_strm_V_data_V_0_data_out = AXI_video_strm_V_data_V_0_payload_A.read();
    }
}

void AXIvideo2xfMat::thread_AXI_video_strm_V_data_V_0_load_A() {
    AXI_video_strm_V_data_V_0_load_A = (AXI_video_strm_V_data_V_0_state_cmp_full.read() & ~AXI_video_strm_V_data_V_0_sel_wr.read());
}

void AXIvideo2xfMat::thread_AXI_video_strm_V_data_V_0_load_B() {
    AXI_video_strm_V_data_V_0_load_B = (AXI_video_strm_V_data_V_0_sel_wr.read() & AXI_video_strm_V_data_V_0_state_cmp_full.read());
}

void AXIvideo2xfMat::thread_AXI_video_strm_V_data_V_0_sel() {
    AXI_video_strm_V_data_V_0_sel = AXI_video_strm_V_data_V_0_sel_rd.read();
}

void AXIvideo2xfMat::thread_AXI_video_strm_V_data_V_0_state_cmp_full() {
    AXI_video_strm_V_data_V_0_state_cmp_full =  (sc_logic) ((!AXI_video_strm_V_data_V_0_state.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(AXI_video_strm_V_data_V_0_state.read() != ap_const_lv2_1))[0];
}

void AXIvideo2xfMat::thread_AXI_video_strm_V_data_V_0_vld_in() {
    AXI_video_strm_V_data_V_0_vld_in = p_src_TVALID.read();
}

void AXIvideo2xfMat::thread_AXI_video_strm_V_data_V_0_vld_out() {
    AXI_video_strm_V_data_V_0_vld_out = AXI_video_strm_V_data_V_0_state.read()[0];
}

void AXIvideo2xfMat::thread_AXI_video_strm_V_dest_V_0_ack_out() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(AXI_video_strm_V_data_V_0_vld_out.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_i_reg_319.read()) && 
          !(esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_i_reg_319.read()) && esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_data_V_0_vld_out.read()))) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && 
          esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op65_read_state5.read()) && 
          esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0)))) {
        AXI_video_strm_V_dest_V_0_ack_out = ap_const_logic_1;
    } else {
        AXI_video_strm_V_dest_V_0_ack_out = ap_const_logic_0;
    }
}

void AXIvideo2xfMat::thread_AXI_video_strm_V_dest_V_0_vld_in() {
    AXI_video_strm_V_dest_V_0_vld_in = p_src_TVALID.read();
}

void AXIvideo2xfMat::thread_AXI_video_strm_V_last_V_0_ack_in() {
    AXI_video_strm_V_last_V_0_ack_in = AXI_video_strm_V_last_V_0_state.read()[1];
}

void AXIvideo2xfMat::thread_AXI_video_strm_V_last_V_0_ack_out() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(AXI_video_strm_V_data_V_0_vld_out.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_i_reg_319.read()) && 
          !(esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_i_reg_319.read()) && esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_data_V_0_vld_out.read()))) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && 
          esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op65_read_state5.read()) && 
          esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0)))) {
        AXI_video_strm_V_last_V_0_ack_out = ap_const_logic_1;
    } else {
        AXI_video_strm_V_last_V_0_ack_out = ap_const_logic_0;
    }
}

void AXIvideo2xfMat::thread_AXI_video_strm_V_last_V_0_data_out() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_last_V_0_sel.read())) {
        AXI_video_strm_V_last_V_0_data_out = AXI_video_strm_V_last_V_0_payload_B.read();
    } else {
        AXI_video_strm_V_last_V_0_data_out = AXI_video_strm_V_last_V_0_payload_A.read();
    }
}

void AXIvideo2xfMat::thread_AXI_video_strm_V_last_V_0_load_A() {
    AXI_video_strm_V_last_V_0_load_A = (AXI_video_strm_V_last_V_0_state_cmp_full.read() & ~AXI_video_strm_V_last_V_0_sel_wr.read());
}

void AXIvideo2xfMat::thread_AXI_video_strm_V_last_V_0_load_B() {
    AXI_video_strm_V_last_V_0_load_B = (AXI_video_strm_V_last_V_0_sel_wr.read() & AXI_video_strm_V_last_V_0_state_cmp_full.read());
}

void AXIvideo2xfMat::thread_AXI_video_strm_V_last_V_0_sel() {
    AXI_video_strm_V_last_V_0_sel = AXI_video_strm_V_last_V_0_sel_rd.read();
}

void AXIvideo2xfMat::thread_AXI_video_strm_V_last_V_0_state_cmp_full() {
    AXI_video_strm_V_last_V_0_state_cmp_full =  (sc_logic) ((!AXI_video_strm_V_last_V_0_state.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(AXI_video_strm_V_last_V_0_state.read() != ap_const_lv2_1))[0];
}

void AXIvideo2xfMat::thread_AXI_video_strm_V_last_V_0_vld_in() {
    AXI_video_strm_V_last_V_0_vld_in = p_src_TVALID.read();
}

void AXIvideo2xfMat::thread_AXI_video_strm_V_last_V_0_vld_out() {
    AXI_video_strm_V_last_V_0_vld_out = AXI_video_strm_V_last_V_0_state.read()[0];
}

void AXIvideo2xfMat::thread_AXI_video_strm_V_user_V_0_ack_in() {
    AXI_video_strm_V_user_V_0_ack_in = AXI_video_strm_V_user_V_0_state.read()[1];
}

void AXIvideo2xfMat::thread_AXI_video_strm_V_user_V_0_ack_out() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(AXI_video_strm_V_data_V_0_vld_out.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_i_reg_319.read()) && 
          !(esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_i_reg_319.read()) && esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_data_V_0_vld_out.read()))) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && 
          esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op65_read_state5.read()) && 
          esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0)))) {
        AXI_video_strm_V_user_V_0_ack_out = ap_const_logic_1;
    } else {
        AXI_video_strm_V_user_V_0_ack_out = ap_const_logic_0;
    }
}

void AXIvideo2xfMat::thread_AXI_video_strm_V_user_V_0_data_out() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_user_V_0_sel.read())) {
        AXI_video_strm_V_user_V_0_data_out = AXI_video_strm_V_user_V_0_payload_B.read();
    } else {
        AXI_video_strm_V_user_V_0_data_out = AXI_video_strm_V_user_V_0_payload_A.read();
    }
}

void AXIvideo2xfMat::thread_AXI_video_strm_V_user_V_0_load_A() {
    AXI_video_strm_V_user_V_0_load_A = (AXI_video_strm_V_user_V_0_state_cmp_full.read() & ~AXI_video_strm_V_user_V_0_sel_wr.read());
}

void AXIvideo2xfMat::thread_AXI_video_strm_V_user_V_0_load_B() {
    AXI_video_strm_V_user_V_0_load_B = (AXI_video_strm_V_user_V_0_sel_wr.read() & AXI_video_strm_V_user_V_0_state_cmp_full.read());
}

void AXIvideo2xfMat::thread_AXI_video_strm_V_user_V_0_sel() {
    AXI_video_strm_V_user_V_0_sel = AXI_video_strm_V_user_V_0_sel_rd.read();
}

void AXIvideo2xfMat::thread_AXI_video_strm_V_user_V_0_state_cmp_full() {
    AXI_video_strm_V_user_V_0_state_cmp_full =  (sc_logic) ((!AXI_video_strm_V_user_V_0_state.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(AXI_video_strm_V_user_V_0_state.read() != ap_const_lv2_1))[0];
}

void AXIvideo2xfMat::thread_AXI_video_strm_V_user_V_0_vld_in() {
    AXI_video_strm_V_user_V_0_vld_in = p_src_TVALID.read();
}

void AXIvideo2xfMat::thread_AXI_video_strm_V_user_V_0_vld_out() {
    AXI_video_strm_V_user_V_0_vld_out = AXI_video_strm_V_user_V_0_state.read()[0];
}

void AXIvideo2xfMat::thread_ap_CS_fsm_pp1_stage0() {
    ap_CS_fsm_pp1_stage0 = ap_CS_fsm.read()[4];
}

void AXIvideo2xfMat::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void AXIvideo2xfMat::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void AXIvideo2xfMat::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void AXIvideo2xfMat::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void AXIvideo2xfMat::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[5];
}

void AXIvideo2xfMat::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[6];
}

void AXIvideo2xfMat::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[7];
}

void AXIvideo2xfMat::thread_ap_block_pp1_stage0() {
    ap_block_pp1_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void AXIvideo2xfMat::thread_ap_block_pp1_stage0_01001() {
    ap_block_pp1_stage0_01001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_data_V_0_vld_out.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op65_read_state5.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_1, tmp_138_i_reg_431.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, img_data_V_full_n.read())));
}

void AXIvideo2xfMat::thread_ap_block_pp1_stage0_11001() {
    ap_block_pp1_stage0_11001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_data_V_0_vld_out.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op65_read_state5.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_1, tmp_138_i_reg_431.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, img_data_V_full_n.read())));
}

void AXIvideo2xfMat::thread_ap_block_pp1_stage0_subdone() {
    ap_block_pp1_stage0_subdone = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_data_V_0_vld_out.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op65_read_state5.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_1, tmp_138_i_reg_431.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, img_data_V_full_n.read())));
}

void AXIvideo2xfMat::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, img_rows_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_cols_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_rows_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_cols_out_full_n.read()));
}

void AXIvideo2xfMat::thread_ap_block_state5_pp1_stage0_iter0() {
    ap_block_state5_pp1_stage0_iter0 = (esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_data_V_0_vld_out.read()) && esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op65_read_state5.read()));
}

void AXIvideo2xfMat::thread_ap_block_state6_pp1_stage0_iter1() {
    ap_block_state6_pp1_stage0_iter1 = (esl_seteq<1,1,1>(ap_const_lv1_1, tmp_138_i_reg_431.read()) && esl_seteq<1,1,1>(ap_const_logic_0, img_data_V_full_n.read()));
}

void AXIvideo2xfMat::thread_ap_block_state8() {
    ap_block_state8 = (esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_i_reg_319.read()) && esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_data_V_0_vld_out.read()));
}

void AXIvideo2xfMat::thread_ap_condition_568() {
    ap_condition_568 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0));
}

void AXIvideo2xfMat::thread_ap_condition_pp1_exit_iter0_state5() {
    if (esl_seteq<1,1,1>(ap_const_lv1_0, tmp_138_i_fu_367_p2.read())) {
        ap_condition_pp1_exit_iter0_state5 = ap_const_logic_1;
    } else {
        ap_condition_pp1_exit_iter0_state5 = ap_const_logic_0;
    }
}

void AXIvideo2xfMat::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_137_i_fu_352_p2.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void AXIvideo2xfMat::thread_ap_enable_pp1() {
    ap_enable_pp1 = (ap_idle_pp1.read() ^ ap_const_logic_1);
}

void AXIvideo2xfMat::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void AXIvideo2xfMat::thread_ap_idle_pp1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp1_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp1_iter1.read()))) {
        ap_idle_pp1 = ap_const_logic_1;
    } else {
        ap_idle_pp1 = ap_const_logic_0;
    }
}

void AXIvideo2xfMat::thread_ap_phi_mux_axi_data_V_1_i_phi_fu_238_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, tmp_138_i_reg_431.read()))) {
        ap_phi_mux_axi_data_V_1_i_phi_fu_238_p4 = p_Val2_s_reg_282.read();
    } else {
        ap_phi_mux_axi_data_V_1_i_phi_fu_238_p4 = axi_data_V_1_i_reg_235.read();
    }
}

void AXIvideo2xfMat::thread_ap_phi_mux_eol_2_i_phi_fu_322_p4() {
    ap_phi_mux_eol_2_i_phi_fu_322_p4 = eol_2_i_reg_319.read();
}

void AXIvideo2xfMat::thread_ap_phi_mux_eol_i_phi_fu_250_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, tmp_138_i_reg_431.read()))) {
        ap_phi_mux_eol_i_phi_fu_250_p4 = axi_last_V_2_i_reg_269.read();
    } else {
        ap_phi_mux_eol_i_phi_fu_250_p4 = eol_i_reg_246.read();
    }
}

void AXIvideo2xfMat::thread_ap_phi_mux_eol_phi_fu_227_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, tmp_138_i_reg_431.read()))) {
        ap_phi_mux_eol_phi_fu_227_p4 = axi_last_V_2_i_reg_269.read();
    } else {
        ap_phi_mux_eol_phi_fu_227_p4 = eol_reg_224.read();
    }
}

void AXIvideo2xfMat::thread_ap_phi_reg_pp1_iter0_axi_last_V_2_i_reg_269() {
    ap_phi_reg_pp1_iter0_axi_last_V_2_i_reg_269 =  (sc_lv<1>) ("X");
}

void AXIvideo2xfMat::thread_ap_phi_reg_pp1_iter0_p_Val2_s_reg_282() {
    ap_phi_reg_pp1_iter0_p_Val2_s_reg_282 = "XXXXXXXX";
}

void AXIvideo2xfMat::thread_ap_predicate_op65_read_state5() {
    ap_predicate_op65_read_state5 = (esl_seteq<1,1,1>(ap_const_lv1_1, tmp_138_i_fu_367_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, brmerge_i_fu_381_p2.read()));
}

void AXIvideo2xfMat::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_137_i_fu_352_p2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void AXIvideo2xfMat::thread_brmerge_i_fu_381_p2() {
    brmerge_i_fu_381_p2 = (sof_1_i_fu_136.read() | ap_phi_mux_eol_i_phi_fu_250_p4.read());
}

void AXIvideo2xfMat::thread_i_cast_cast_i_fu_348_p1() {
    i_cast_cast_i_fu_348_p1 = esl_zext<12,11>(i_i_reg_213.read());
}

void AXIvideo2xfMat::thread_i_fu_357_p2() {
    i_fu_357_p2 = (!i_i_reg_213.read().is_01() || !ap_const_lv11_1.is_01())? sc_lv<11>(): (sc_biguint<11>(i_i_reg_213.read()) + sc_biguint<11>(ap_const_lv11_1));
}

void AXIvideo2xfMat::thread_img_cols_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        img_cols_blk_n = img_cols_empty_n.read();
    } else {
        img_cols_blk_n = ap_const_logic_1;
    }
}

void AXIvideo2xfMat::thread_img_cols_out_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        img_cols_out_blk_n = img_cols_out_full_n.read();
    } else {
        img_cols_out_blk_n = ap_const_logic_1;
    }
}

void AXIvideo2xfMat::thread_img_cols_out_din() {
    img_cols_out_din = img_cols_dout.read();
}

void AXIvideo2xfMat::thread_img_cols_out_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, img_rows_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_cols_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_rows_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_cols_out_full_n.read())))) {
        img_cols_out_write = ap_const_logic_1;
    } else {
        img_cols_out_write = ap_const_logic_0;
    }
}

void AXIvideo2xfMat::thread_img_cols_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, img_rows_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_cols_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_rows_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_cols_out_full_n.read())))) {
        img_cols_read = ap_const_logic_1;
    } else {
        img_cols_read = ap_const_logic_0;
    }
}

void AXIvideo2xfMat::thread_img_data_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, tmp_138_i_reg_431.read()))) {
        img_data_V_blk_n = img_data_V_full_n.read();
    } else {
        img_data_V_blk_n = ap_const_logic_1;
    }
}

void AXIvideo2xfMat::thread_img_data_V_din() {
    img_data_V_din = p_Val2_s_reg_282.read();
}

void AXIvideo2xfMat::thread_img_data_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, tmp_138_i_reg_431.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0))) {
        img_data_V_write = ap_const_logic_1;
    } else {
        img_data_V_write = ap_const_logic_0;
    }
}

void AXIvideo2xfMat::thread_img_rows_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        img_rows_blk_n = img_rows_empty_n.read();
    } else {
        img_rows_blk_n = ap_const_logic_1;
    }
}

void AXIvideo2xfMat::thread_img_rows_out_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        img_rows_out_blk_n = img_rows_out_full_n.read();
    } else {
        img_rows_out_blk_n = ap_const_logic_1;
    }
}

void AXIvideo2xfMat::thread_img_rows_out_din() {
    img_rows_out_din = img_rows_dout.read();
}

void AXIvideo2xfMat::thread_img_rows_out_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, img_rows_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_cols_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_rows_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_cols_out_full_n.read())))) {
        img_rows_out_write = ap_const_logic_1;
    } else {
        img_rows_out_write = ap_const_logic_0;
    }
}

void AXIvideo2xfMat::thread_img_rows_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, img_rows_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_cols_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_rows_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_cols_out_full_n.read())))) {
        img_rows_read = ap_const_logic_1;
    } else {
        img_rows_read = ap_const_logic_0;
    }
}

void AXIvideo2xfMat::thread_j_cast_cast_i_fu_363_p1() {
    j_cast_cast_i_fu_363_p1 = esl_zext<12,11>(j_i_reg_258.read());
}

void AXIvideo2xfMat::thread_j_fu_372_p2() {
    j_fu_372_p2 = (!j_i_reg_258.read().is_01() || !ap_const_lv11_1.is_01())? sc_lv<11>(): (sc_biguint<11>(j_i_reg_258.read()) + sc_biguint<11>(ap_const_lv11_1));
}

void AXIvideo2xfMat::thread_p_src_TDATA_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, tmp_138_i_fu_367_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, brmerge_i_fu_381_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_i_reg_319.read())))) {
        p_src_TDATA_blk_n = AXI_video_strm_V_data_V_0_state.read()[0];
    } else {
        p_src_TDATA_blk_n = ap_const_logic_1;
    }
}

void AXIvideo2xfMat::thread_p_src_TREADY() {
    p_src_TREADY = AXI_video_strm_V_dest_V_0_state.read()[1];
}

void AXIvideo2xfMat::thread_tmp_137_i_fu_352_p2() {
    tmp_137_i_fu_352_p2 = (!i_cast_cast_i_fu_348_p1.read().is_01() || !img_rows_read_reg_392.read().is_01())? sc_lv<1>(): (sc_bigint<12>(i_cast_cast_i_fu_348_p1.read()) < sc_bigint<12>(img_rows_read_reg_392.read()));
}

void AXIvideo2xfMat::thread_tmp_138_i_fu_367_p2() {
    tmp_138_i_fu_367_p2 = (!j_cast_cast_i_fu_363_p1.read().is_01() || !img_cols_read_reg_397.read().is_01())? sc_lv<1>(): (sc_bigint<12>(j_cast_cast_i_fu_363_p1.read()) < sc_bigint<12>(img_cols_read_reg_397.read()));
}

void AXIvideo2xfMat::thread_tmp_user_V_fu_339_p1() {
    tmp_user_V_fu_339_p1 = AXI_video_strm_V_user_V_0_data_out.read();
}

void AXIvideo2xfMat::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, img_rows_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_cols_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_rows_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_cols_out_full_n.read())))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(AXI_video_strm_V_data_V_0_vld_out.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_user_V_fu_339_p1.read()))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(AXI_video_strm_V_data_V_0_vld_out.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_user_V_fu_339_p1.read()))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_137_i_fu_352_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            }
            break;
        case 16 : 
            if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_138_i_fu_367_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_138_i_fu_367_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state7;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            }
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 64 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_i_reg_319.read()) && !(esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_i_reg_319.read()) && esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_data_V_0_vld_out.read())))) {
                ap_NS_fsm = ap_ST_fsm_state8;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && !(esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_i_reg_319.read()) && esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_data_V_0_vld_out.read())) && esl_seteq<1,1,1>(ap_const_lv1_1, ap_phi_mux_eol_2_i_phi_fu_322_p4.read()))) {
                ap_NS_fsm = ap_ST_fsm_state9;
            } else {
                ap_NS_fsm = ap_ST_fsm_state8;
            }
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        default : 
            ap_NS_fsm = "XXXXXXXX";
            break;
    }
}

}

