-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.3
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity warp_stream_accel is
port (
    p_src_TDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    p_src_TKEEP : IN STD_LOGIC_VECTOR (0 downto 0);
    p_src_TSTRB : IN STD_LOGIC_VECTOR (0 downto 0);
    p_src_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    p_src_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    p_src_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    p_src_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    p_dst_TDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_dst_TKEEP : OUT STD_LOGIC_VECTOR (0 downto 0);
    p_dst_TSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
    p_dst_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    p_dst_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    p_dst_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
    p_dst_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0);
    R_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    R_ce0 : OUT STD_LOGIC;
    R_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    R_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    R_we0 : OUT STD_LOGIC;
    R_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    R_ce1 : OUT STD_LOGIC;
    R_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    R_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    R_we1 : OUT STD_LOGIC;
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    p_src_TVALID : IN STD_LOGIC;
    p_src_TREADY : OUT STD_LOGIC;
    p_dst_TVALID : OUT STD_LOGIC;
    p_dst_TREADY : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC );
end;


architecture behav of warp_stream_accel is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "warp_stream_accel,hls_ip_2018_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=9.912812,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=116,HLS_SYN_DSP=55,HLS_SYN_FF=13221,HLS_SYN_LUT=23229,HLS_VERSION=2018_3}";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";

    signal ap_rst_n_inv : STD_LOGIC;
    signal Block_proc_U0_ap_start : STD_LOGIC;
    signal Block_proc_U0_ap_done : STD_LOGIC;
    signal Block_proc_U0_ap_continue : STD_LOGIC;
    signal Block_proc_U0_ap_idle : STD_LOGIC;
    signal Block_proc_U0_ap_ready : STD_LOGIC;
    signal Block_proc_U0_imgInput1_rows_out_din : STD_LOGIC_VECTOR (11 downto 0);
    signal Block_proc_U0_imgInput1_rows_out_write : STD_LOGIC;
    signal Block_proc_U0_imgInput1_cols_out_din : STD_LOGIC_VECTOR (11 downto 0);
    signal Block_proc_U0_imgInput1_cols_out_write : STD_LOGIC;
    signal Block_proc_U0_imgOutput1_rows_out_din : STD_LOGIC_VECTOR (11 downto 0);
    signal Block_proc_U0_imgOutput1_rows_out_write : STD_LOGIC;
    signal Block_proc_U0_imgOutput1_cols_out_din : STD_LOGIC_VECTOR (11 downto 0);
    signal Block_proc_U0_imgOutput1_cols_out_write : STD_LOGIC;
    signal AXIvideo2xfMat_U0_ap_start : STD_LOGIC;
    signal AXIvideo2xfMat_U0_ap_done : STD_LOGIC;
    signal AXIvideo2xfMat_U0_ap_continue : STD_LOGIC;
    signal AXIvideo2xfMat_U0_ap_idle : STD_LOGIC;
    signal AXIvideo2xfMat_U0_ap_ready : STD_LOGIC;
    signal AXIvideo2xfMat_U0_p_src_TREADY : STD_LOGIC;
    signal AXIvideo2xfMat_U0_img_rows_read : STD_LOGIC;
    signal AXIvideo2xfMat_U0_img_cols_read : STD_LOGIC;
    signal AXIvideo2xfMat_U0_img_data_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal AXIvideo2xfMat_U0_img_data_V_write : STD_LOGIC;
    signal AXIvideo2xfMat_U0_img_rows_out_din : STD_LOGIC_VECTOR (11 downto 0);
    signal AXIvideo2xfMat_U0_img_rows_out_write : STD_LOGIC;
    signal AXIvideo2xfMat_U0_img_cols_out_din : STD_LOGIC_VECTOR (11 downto 0);
    signal AXIvideo2xfMat_U0_img_cols_out_write : STD_LOGIC;
    signal warpTransform_U0_ap_start : STD_LOGIC;
    signal warpTransform_U0_start_out : STD_LOGIC;
    signal warpTransform_U0_start_write : STD_LOGIC;
    signal warpTransform_U0_p_src_mat_rows_read : STD_LOGIC;
    signal warpTransform_U0_p_src_mat_cols_read : STD_LOGIC;
    signal warpTransform_U0_p_src_mat_data_V_read : STD_LOGIC;
    signal warpTransform_U0_p_dst_mat_rows_read : STD_LOGIC;
    signal warpTransform_U0_p_dst_mat_cols_read : STD_LOGIC;
    signal warpTransform_U0_p_dst_mat_data_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal warpTransform_U0_p_dst_mat_data_V_write : STD_LOGIC;
    signal warpTransform_U0_P_matrix_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal warpTransform_U0_P_matrix_ce0 : STD_LOGIC;
    signal warpTransform_U0_P_matrix_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal warpTransform_U0_P_matrix_we0 : STD_LOGIC;
    signal warpTransform_U0_P_matrix_address1 : STD_LOGIC_VECTOR (3 downto 0);
    signal warpTransform_U0_P_matrix_ce1 : STD_LOGIC;
    signal warpTransform_U0_P_matrix_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal warpTransform_U0_P_matrix_we1 : STD_LOGIC;
    signal warpTransform_U0_p_dst_mat_rows_out_din : STD_LOGIC_VECTOR (11 downto 0);
    signal warpTransform_U0_p_dst_mat_rows_out_write : STD_LOGIC;
    signal warpTransform_U0_p_dst_mat_cols_out_din : STD_LOGIC_VECTOR (11 downto 0);
    signal warpTransform_U0_p_dst_mat_cols_out_write : STD_LOGIC;
    signal warpTransform_U0_ap_done : STD_LOGIC;
    signal warpTransform_U0_ap_ready : STD_LOGIC;
    signal warpTransform_U0_ap_idle : STD_LOGIC;
    signal warpTransform_U0_ap_continue : STD_LOGIC;
    signal xfMat2AXIvideo_U0_ap_start : STD_LOGIC;
    signal xfMat2AXIvideo_U0_ap_done : STD_LOGIC;
    signal xfMat2AXIvideo_U0_ap_continue : STD_LOGIC;
    signal xfMat2AXIvideo_U0_ap_idle : STD_LOGIC;
    signal xfMat2AXIvideo_U0_ap_ready : STD_LOGIC;
    signal xfMat2AXIvideo_U0_img_rows_read : STD_LOGIC;
    signal xfMat2AXIvideo_U0_img_cols_read : STD_LOGIC;
    signal xfMat2AXIvideo_U0_img_data_V_read : STD_LOGIC;
    signal xfMat2AXIvideo_U0_p_dst_TDATA : STD_LOGIC_VECTOR (7 downto 0);
    signal xfMat2AXIvideo_U0_p_dst_TVALID : STD_LOGIC;
    signal xfMat2AXIvideo_U0_p_dst_TKEEP : STD_LOGIC_VECTOR (0 downto 0);
    signal xfMat2AXIvideo_U0_p_dst_TSTRB : STD_LOGIC_VECTOR (0 downto 0);
    signal xfMat2AXIvideo_U0_p_dst_TUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal xfMat2AXIvideo_U0_p_dst_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal xfMat2AXIvideo_U0_p_dst_TID : STD_LOGIC_VECTOR (0 downto 0);
    signal xfMat2AXIvideo_U0_p_dst_TDEST : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sync_continue : STD_LOGIC;
    signal imgInput1_rows_c_full_n : STD_LOGIC;
    signal imgInput1_rows_c_dout : STD_LOGIC_VECTOR (11 downto 0);
    signal imgInput1_rows_c_empty_n : STD_LOGIC;
    signal imgInput1_cols_c_full_n : STD_LOGIC;
    signal imgInput1_cols_c_dout : STD_LOGIC_VECTOR (11 downto 0);
    signal imgInput1_cols_c_empty_n : STD_LOGIC;
    signal imgOutput1_rows_c_full_n : STD_LOGIC;
    signal imgOutput1_rows_c_dout : STD_LOGIC_VECTOR (11 downto 0);
    signal imgOutput1_rows_c_empty_n : STD_LOGIC;
    signal imgOutput1_cols_c_full_n : STD_LOGIC;
    signal imgOutput1_cols_c_dout : STD_LOGIC_VECTOR (11 downto 0);
    signal imgOutput1_cols_c_empty_n : STD_LOGIC;
    signal imgInput1_data_V_full_n : STD_LOGIC;
    signal imgInput1_data_V_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal imgInput1_data_V_empty_n : STD_LOGIC;
    signal imgInput1_rows_c4_full_n : STD_LOGIC;
    signal imgInput1_rows_c4_dout : STD_LOGIC_VECTOR (11 downto 0);
    signal imgInput1_rows_c4_empty_n : STD_LOGIC;
    signal imgInput1_cols_c5_full_n : STD_LOGIC;
    signal imgInput1_cols_c5_dout : STD_LOGIC_VECTOR (11 downto 0);
    signal imgInput1_cols_c5_empty_n : STD_LOGIC;
    signal imgOutput1_data_V_full_n : STD_LOGIC;
    signal imgOutput1_data_V_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal imgOutput1_data_V_empty_n : STD_LOGIC;
    signal imgOutput1_rows_c6_full_n : STD_LOGIC;
    signal imgOutput1_rows_c6_dout : STD_LOGIC_VECTOR (11 downto 0);
    signal imgOutput1_rows_c6_empty_n : STD_LOGIC;
    signal imgOutput1_cols_c7_full_n : STD_LOGIC;
    signal imgOutput1_cols_c7_dout : STD_LOGIC_VECTOR (11 downto 0);
    signal imgOutput1_cols_c7_empty_n : STD_LOGIC;
    signal ap_sync_done : STD_LOGIC;
    signal ap_sync_ready : STD_LOGIC;
    signal ap_sync_reg_Block_proc_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_Block_proc_U0_ap_ready : STD_LOGIC;
    signal Block_proc_U0_ap_ready_count : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal ap_sync_reg_AXIvideo2xfMat_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_AXIvideo2xfMat_U0_ap_ready : STD_LOGIC;
    signal AXIvideo2xfMat_U0_ap_ready_count : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal ap_sync_reg_warpTransform_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_warpTransform_U0_ap_ready : STD_LOGIC;
    signal warpTransform_U0_ap_ready_count : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal Block_proc_U0_start_full_n : STD_LOGIC;
    signal Block_proc_U0_start_write : STD_LOGIC;
    signal AXIvideo2xfMat_U0_start_full_n : STD_LOGIC;
    signal AXIvideo2xfMat_U0_start_write : STD_LOGIC;
    signal start_for_xfMat2AXIvideo_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_xfMat2AXIvideo_U0_full_n : STD_LOGIC;
    signal start_for_xfMat2AXIvideo_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_xfMat2AXIvideo_U0_empty_n : STD_LOGIC;
    signal xfMat2AXIvideo_U0_start_full_n : STD_LOGIC;
    signal xfMat2AXIvideo_U0_start_write : STD_LOGIC;

    component Block_proc IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        imgInput1_rows_out_din : OUT STD_LOGIC_VECTOR (11 downto 0);
        imgInput1_rows_out_full_n : IN STD_LOGIC;
        imgInput1_rows_out_write : OUT STD_LOGIC;
        imgInput1_cols_out_din : OUT STD_LOGIC_VECTOR (11 downto 0);
        imgInput1_cols_out_full_n : IN STD_LOGIC;
        imgInput1_cols_out_write : OUT STD_LOGIC;
        imgOutput1_rows_out_din : OUT STD_LOGIC_VECTOR (11 downto 0);
        imgOutput1_rows_out_full_n : IN STD_LOGIC;
        imgOutput1_rows_out_write : OUT STD_LOGIC;
        imgOutput1_cols_out_din : OUT STD_LOGIC_VECTOR (11 downto 0);
        imgOutput1_cols_out_full_n : IN STD_LOGIC;
        imgOutput1_cols_out_write : OUT STD_LOGIC );
    end component;


    component AXIvideo2xfMat IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        p_src_TDATA : IN STD_LOGIC_VECTOR (7 downto 0);
        p_src_TVALID : IN STD_LOGIC;
        p_src_TREADY : OUT STD_LOGIC;
        p_src_TKEEP : IN STD_LOGIC_VECTOR (0 downto 0);
        p_src_TSTRB : IN STD_LOGIC_VECTOR (0 downto 0);
        p_src_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        p_src_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        p_src_TID : IN STD_LOGIC_VECTOR (0 downto 0);
        p_src_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
        img_rows_dout : IN STD_LOGIC_VECTOR (11 downto 0);
        img_rows_empty_n : IN STD_LOGIC;
        img_rows_read : OUT STD_LOGIC;
        img_cols_dout : IN STD_LOGIC_VECTOR (11 downto 0);
        img_cols_empty_n : IN STD_LOGIC;
        img_cols_read : OUT STD_LOGIC;
        img_data_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        img_data_V_full_n : IN STD_LOGIC;
        img_data_V_write : OUT STD_LOGIC;
        img_rows_out_din : OUT STD_LOGIC_VECTOR (11 downto 0);
        img_rows_out_full_n : IN STD_LOGIC;
        img_rows_out_write : OUT STD_LOGIC;
        img_cols_out_din : OUT STD_LOGIC_VECTOR (11 downto 0);
        img_cols_out_full_n : IN STD_LOGIC;
        img_cols_out_write : OUT STD_LOGIC );
    end component;


    component warpTransform IS
    port (
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        p_src_mat_rows_dout : IN STD_LOGIC_VECTOR (11 downto 0);
        p_src_mat_rows_empty_n : IN STD_LOGIC;
        p_src_mat_rows_read : OUT STD_LOGIC;
        p_src_mat_cols_dout : IN STD_LOGIC_VECTOR (11 downto 0);
        p_src_mat_cols_empty_n : IN STD_LOGIC;
        p_src_mat_cols_read : OUT STD_LOGIC;
        p_src_mat_data_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        p_src_mat_data_V_empty_n : IN STD_LOGIC;
        p_src_mat_data_V_read : OUT STD_LOGIC;
        p_dst_mat_rows_dout : IN STD_LOGIC_VECTOR (11 downto 0);
        p_dst_mat_rows_empty_n : IN STD_LOGIC;
        p_dst_mat_rows_read : OUT STD_LOGIC;
        p_dst_mat_cols_dout : IN STD_LOGIC_VECTOR (11 downto 0);
        p_dst_mat_cols_empty_n : IN STD_LOGIC;
        p_dst_mat_cols_read : OUT STD_LOGIC;
        p_dst_mat_data_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_dst_mat_data_V_full_n : IN STD_LOGIC;
        p_dst_mat_data_V_write : OUT STD_LOGIC;
        P_matrix_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        P_matrix_ce0 : OUT STD_LOGIC;
        P_matrix_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        P_matrix_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        P_matrix_we0 : OUT STD_LOGIC;
        P_matrix_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
        P_matrix_ce1 : OUT STD_LOGIC;
        P_matrix_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        P_matrix_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        P_matrix_we1 : OUT STD_LOGIC;
        p_dst_mat_rows_out_din : OUT STD_LOGIC_VECTOR (11 downto 0);
        p_dst_mat_rows_out_full_n : IN STD_LOGIC;
        p_dst_mat_rows_out_write : OUT STD_LOGIC;
        p_dst_mat_cols_out_din : OUT STD_LOGIC_VECTOR (11 downto 0);
        p_dst_mat_cols_out_full_n : IN STD_LOGIC;
        p_dst_mat_cols_out_write : OUT STD_LOGIC;
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;


    component xfMat2AXIvideo IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        img_rows_dout : IN STD_LOGIC_VECTOR (11 downto 0);
        img_rows_empty_n : IN STD_LOGIC;
        img_rows_read : OUT STD_LOGIC;
        img_cols_dout : IN STD_LOGIC_VECTOR (11 downto 0);
        img_cols_empty_n : IN STD_LOGIC;
        img_cols_read : OUT STD_LOGIC;
        img_data_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        img_data_V_empty_n : IN STD_LOGIC;
        img_data_V_read : OUT STD_LOGIC;
        p_dst_TDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_dst_TVALID : OUT STD_LOGIC;
        p_dst_TREADY : IN STD_LOGIC;
        p_dst_TKEEP : OUT STD_LOGIC_VECTOR (0 downto 0);
        p_dst_TSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
        p_dst_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        p_dst_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        p_dst_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
        p_dst_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component fifo_w12_d2_A_x IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (11 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (11 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component fifo_w12_d3_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (11 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (11 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component fifo_w8_d1_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (7 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (7 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component start_for_xfMat2Ab3s IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;



begin
    Block_proc_U0 : component Block_proc
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => Block_proc_U0_ap_start,
        ap_done => Block_proc_U0_ap_done,
        ap_continue => Block_proc_U0_ap_continue,
        ap_idle => Block_proc_U0_ap_idle,
        ap_ready => Block_proc_U0_ap_ready,
        imgInput1_rows_out_din => Block_proc_U0_imgInput1_rows_out_din,
        imgInput1_rows_out_full_n => imgInput1_rows_c_full_n,
        imgInput1_rows_out_write => Block_proc_U0_imgInput1_rows_out_write,
        imgInput1_cols_out_din => Block_proc_U0_imgInput1_cols_out_din,
        imgInput1_cols_out_full_n => imgInput1_cols_c_full_n,
        imgInput1_cols_out_write => Block_proc_U0_imgInput1_cols_out_write,
        imgOutput1_rows_out_din => Block_proc_U0_imgOutput1_rows_out_din,
        imgOutput1_rows_out_full_n => imgOutput1_rows_c_full_n,
        imgOutput1_rows_out_write => Block_proc_U0_imgOutput1_rows_out_write,
        imgOutput1_cols_out_din => Block_proc_U0_imgOutput1_cols_out_din,
        imgOutput1_cols_out_full_n => imgOutput1_cols_c_full_n,
        imgOutput1_cols_out_write => Block_proc_U0_imgOutput1_cols_out_write);

    AXIvideo2xfMat_U0 : component AXIvideo2xfMat
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => AXIvideo2xfMat_U0_ap_start,
        ap_done => AXIvideo2xfMat_U0_ap_done,
        ap_continue => AXIvideo2xfMat_U0_ap_continue,
        ap_idle => AXIvideo2xfMat_U0_ap_idle,
        ap_ready => AXIvideo2xfMat_U0_ap_ready,
        p_src_TDATA => p_src_TDATA,
        p_src_TVALID => p_src_TVALID,
        p_src_TREADY => AXIvideo2xfMat_U0_p_src_TREADY,
        p_src_TKEEP => p_src_TKEEP,
        p_src_TSTRB => p_src_TSTRB,
        p_src_TUSER => p_src_TUSER,
        p_src_TLAST => p_src_TLAST,
        p_src_TID => p_src_TID,
        p_src_TDEST => p_src_TDEST,
        img_rows_dout => imgInput1_rows_c_dout,
        img_rows_empty_n => imgInput1_rows_c_empty_n,
        img_rows_read => AXIvideo2xfMat_U0_img_rows_read,
        img_cols_dout => imgInput1_cols_c_dout,
        img_cols_empty_n => imgInput1_cols_c_empty_n,
        img_cols_read => AXIvideo2xfMat_U0_img_cols_read,
        img_data_V_din => AXIvideo2xfMat_U0_img_data_V_din,
        img_data_V_full_n => imgInput1_data_V_full_n,
        img_data_V_write => AXIvideo2xfMat_U0_img_data_V_write,
        img_rows_out_din => AXIvideo2xfMat_U0_img_rows_out_din,
        img_rows_out_full_n => imgInput1_rows_c4_full_n,
        img_rows_out_write => AXIvideo2xfMat_U0_img_rows_out_write,
        img_cols_out_din => AXIvideo2xfMat_U0_img_cols_out_din,
        img_cols_out_full_n => imgInput1_cols_c5_full_n,
        img_cols_out_write => AXIvideo2xfMat_U0_img_cols_out_write);

    warpTransform_U0 : component warpTransform
    port map (
        ap_start => warpTransform_U0_ap_start,
        start_full_n => start_for_xfMat2AXIvideo_U0_full_n,
        start_out => warpTransform_U0_start_out,
        start_write => warpTransform_U0_start_write,
        p_src_mat_rows_dout => imgInput1_rows_c4_dout,
        p_src_mat_rows_empty_n => imgInput1_rows_c4_empty_n,
        p_src_mat_rows_read => warpTransform_U0_p_src_mat_rows_read,
        p_src_mat_cols_dout => imgInput1_cols_c5_dout,
        p_src_mat_cols_empty_n => imgInput1_cols_c5_empty_n,
        p_src_mat_cols_read => warpTransform_U0_p_src_mat_cols_read,
        p_src_mat_data_V_dout => imgInput1_data_V_dout,
        p_src_mat_data_V_empty_n => imgInput1_data_V_empty_n,
        p_src_mat_data_V_read => warpTransform_U0_p_src_mat_data_V_read,
        p_dst_mat_rows_dout => imgOutput1_rows_c_dout,
        p_dst_mat_rows_empty_n => imgOutput1_rows_c_empty_n,
        p_dst_mat_rows_read => warpTransform_U0_p_dst_mat_rows_read,
        p_dst_mat_cols_dout => imgOutput1_cols_c_dout,
        p_dst_mat_cols_empty_n => imgOutput1_cols_c_empty_n,
        p_dst_mat_cols_read => warpTransform_U0_p_dst_mat_cols_read,
        p_dst_mat_data_V_din => warpTransform_U0_p_dst_mat_data_V_din,
        p_dst_mat_data_V_full_n => imgOutput1_data_V_full_n,
        p_dst_mat_data_V_write => warpTransform_U0_p_dst_mat_data_V_write,
        P_matrix_address0 => warpTransform_U0_P_matrix_address0,
        P_matrix_ce0 => warpTransform_U0_P_matrix_ce0,
        P_matrix_d0 => warpTransform_U0_P_matrix_d0,
        P_matrix_q0 => R_q0,
        P_matrix_we0 => warpTransform_U0_P_matrix_we0,
        P_matrix_address1 => warpTransform_U0_P_matrix_address1,
        P_matrix_ce1 => warpTransform_U0_P_matrix_ce1,
        P_matrix_d1 => warpTransform_U0_P_matrix_d1,
        P_matrix_q1 => ap_const_lv32_0,
        P_matrix_we1 => warpTransform_U0_P_matrix_we1,
        p_dst_mat_rows_out_din => warpTransform_U0_p_dst_mat_rows_out_din,
        p_dst_mat_rows_out_full_n => imgOutput1_rows_c6_full_n,
        p_dst_mat_rows_out_write => warpTransform_U0_p_dst_mat_rows_out_write,
        p_dst_mat_cols_out_din => warpTransform_U0_p_dst_mat_cols_out_din,
        p_dst_mat_cols_out_full_n => imgOutput1_cols_c7_full_n,
        p_dst_mat_cols_out_write => warpTransform_U0_p_dst_mat_cols_out_write,
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_done => warpTransform_U0_ap_done,
        ap_ready => warpTransform_U0_ap_ready,
        ap_idle => warpTransform_U0_ap_idle,
        ap_continue => warpTransform_U0_ap_continue);

    xfMat2AXIvideo_U0 : component xfMat2AXIvideo
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => xfMat2AXIvideo_U0_ap_start,
        ap_done => xfMat2AXIvideo_U0_ap_done,
        ap_continue => xfMat2AXIvideo_U0_ap_continue,
        ap_idle => xfMat2AXIvideo_U0_ap_idle,
        ap_ready => xfMat2AXIvideo_U0_ap_ready,
        img_rows_dout => imgOutput1_rows_c6_dout,
        img_rows_empty_n => imgOutput1_rows_c6_empty_n,
        img_rows_read => xfMat2AXIvideo_U0_img_rows_read,
        img_cols_dout => imgOutput1_cols_c7_dout,
        img_cols_empty_n => imgOutput1_cols_c7_empty_n,
        img_cols_read => xfMat2AXIvideo_U0_img_cols_read,
        img_data_V_dout => imgOutput1_data_V_dout,
        img_data_V_empty_n => imgOutput1_data_V_empty_n,
        img_data_V_read => xfMat2AXIvideo_U0_img_data_V_read,
        p_dst_TDATA => xfMat2AXIvideo_U0_p_dst_TDATA,
        p_dst_TVALID => xfMat2AXIvideo_U0_p_dst_TVALID,
        p_dst_TREADY => p_dst_TREADY,
        p_dst_TKEEP => xfMat2AXIvideo_U0_p_dst_TKEEP,
        p_dst_TSTRB => xfMat2AXIvideo_U0_p_dst_TSTRB,
        p_dst_TUSER => xfMat2AXIvideo_U0_p_dst_TUSER,
        p_dst_TLAST => xfMat2AXIvideo_U0_p_dst_TLAST,
        p_dst_TID => xfMat2AXIvideo_U0_p_dst_TID,
        p_dst_TDEST => xfMat2AXIvideo_U0_p_dst_TDEST);

    imgInput1_rows_c_U : component fifo_w12_d2_A_x
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Block_proc_U0_imgInput1_rows_out_din,
        if_full_n => imgInput1_rows_c_full_n,
        if_write => Block_proc_U0_imgInput1_rows_out_write,
        if_dout => imgInput1_rows_c_dout,
        if_empty_n => imgInput1_rows_c_empty_n,
        if_read => AXIvideo2xfMat_U0_img_rows_read);

    imgInput1_cols_c_U : component fifo_w12_d2_A_x
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Block_proc_U0_imgInput1_cols_out_din,
        if_full_n => imgInput1_cols_c_full_n,
        if_write => Block_proc_U0_imgInput1_cols_out_write,
        if_dout => imgInput1_cols_c_dout,
        if_empty_n => imgInput1_cols_c_empty_n,
        if_read => AXIvideo2xfMat_U0_img_cols_read);

    imgOutput1_rows_c_U : component fifo_w12_d3_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Block_proc_U0_imgOutput1_rows_out_din,
        if_full_n => imgOutput1_rows_c_full_n,
        if_write => Block_proc_U0_imgOutput1_rows_out_write,
        if_dout => imgOutput1_rows_c_dout,
        if_empty_n => imgOutput1_rows_c_empty_n,
        if_read => warpTransform_U0_p_dst_mat_rows_read);

    imgOutput1_cols_c_U : component fifo_w12_d3_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Block_proc_U0_imgOutput1_cols_out_din,
        if_full_n => imgOutput1_cols_c_full_n,
        if_write => Block_proc_U0_imgOutput1_cols_out_write,
        if_dout => imgOutput1_cols_c_dout,
        if_empty_n => imgOutput1_cols_c_empty_n,
        if_read => warpTransform_U0_p_dst_mat_cols_read);

    imgInput1_data_V_U : component fifo_w8_d1_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => AXIvideo2xfMat_U0_img_data_V_din,
        if_full_n => imgInput1_data_V_full_n,
        if_write => AXIvideo2xfMat_U0_img_data_V_write,
        if_dout => imgInput1_data_V_dout,
        if_empty_n => imgInput1_data_V_empty_n,
        if_read => warpTransform_U0_p_src_mat_data_V_read);

    imgInput1_rows_c4_U : component fifo_w12_d2_A_x
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => AXIvideo2xfMat_U0_img_rows_out_din,
        if_full_n => imgInput1_rows_c4_full_n,
        if_write => AXIvideo2xfMat_U0_img_rows_out_write,
        if_dout => imgInput1_rows_c4_dout,
        if_empty_n => imgInput1_rows_c4_empty_n,
        if_read => warpTransform_U0_p_src_mat_rows_read);

    imgInput1_cols_c5_U : component fifo_w12_d2_A_x
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => AXIvideo2xfMat_U0_img_cols_out_din,
        if_full_n => imgInput1_cols_c5_full_n,
        if_write => AXIvideo2xfMat_U0_img_cols_out_write,
        if_dout => imgInput1_cols_c5_dout,
        if_empty_n => imgInput1_cols_c5_empty_n,
        if_read => warpTransform_U0_p_src_mat_cols_read);

    imgOutput1_data_V_U : component fifo_w8_d1_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => warpTransform_U0_p_dst_mat_data_V_din,
        if_full_n => imgOutput1_data_V_full_n,
        if_write => warpTransform_U0_p_dst_mat_data_V_write,
        if_dout => imgOutput1_data_V_dout,
        if_empty_n => imgOutput1_data_V_empty_n,
        if_read => xfMat2AXIvideo_U0_img_data_V_read);

    imgOutput1_rows_c6_U : component fifo_w12_d2_A_x
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => warpTransform_U0_p_dst_mat_rows_out_din,
        if_full_n => imgOutput1_rows_c6_full_n,
        if_write => warpTransform_U0_p_dst_mat_rows_out_write,
        if_dout => imgOutput1_rows_c6_dout,
        if_empty_n => imgOutput1_rows_c6_empty_n,
        if_read => xfMat2AXIvideo_U0_img_rows_read);

    imgOutput1_cols_c7_U : component fifo_w12_d2_A_x
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => warpTransform_U0_p_dst_mat_cols_out_din,
        if_full_n => imgOutput1_cols_c7_full_n,
        if_write => warpTransform_U0_p_dst_mat_cols_out_write,
        if_dout => imgOutput1_cols_c7_dout,
        if_empty_n => imgOutput1_cols_c7_empty_n,
        if_read => xfMat2AXIvideo_U0_img_cols_read);

    start_for_xfMat2Ab3s_U : component start_for_xfMat2Ab3s
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_xfMat2AXIvideo_U0_din,
        if_full_n => start_for_xfMat2AXIvideo_U0_full_n,
        if_write => warpTransform_U0_start_write,
        if_dout => start_for_xfMat2AXIvideo_U0_dout,
        if_empty_n => start_for_xfMat2AXIvideo_U0_empty_n,
        if_read => xfMat2AXIvideo_U0_ap_ready);





    ap_sync_reg_AXIvideo2xfMat_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_AXIvideo2xfMat_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_AXIvideo2xfMat_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_AXIvideo2xfMat_U0_ap_ready <= ap_sync_AXIvideo2xfMat_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_Block_proc_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_Block_proc_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_Block_proc_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_Block_proc_U0_ap_ready <= ap_sync_Block_proc_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_warpTransform_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_warpTransform_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_warpTransform_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_warpTransform_U0_ap_ready <= ap_sync_warpTransform_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    AXIvideo2xfMat_U0_ap_ready_count_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_sync_ready = ap_const_logic_1) and (ap_const_logic_0 = AXIvideo2xfMat_U0_ap_ready))) then 
                AXIvideo2xfMat_U0_ap_ready_count <= std_logic_vector(unsigned(AXIvideo2xfMat_U0_ap_ready_count) - unsigned(ap_const_lv2_1));
            elsif (((ap_const_logic_1 = AXIvideo2xfMat_U0_ap_ready) and (ap_sync_ready = ap_const_logic_0))) then 
                AXIvideo2xfMat_U0_ap_ready_count <= std_logic_vector(unsigned(AXIvideo2xfMat_U0_ap_ready_count) + unsigned(ap_const_lv2_1));
            end if; 
        end if;
    end process;

    Block_proc_U0_ap_ready_count_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_sync_ready = ap_const_logic_1) and (ap_const_logic_0 = Block_proc_U0_ap_ready))) then 
                Block_proc_U0_ap_ready_count <= std_logic_vector(unsigned(Block_proc_U0_ap_ready_count) - unsigned(ap_const_lv2_1));
            elsif (((ap_const_logic_1 = Block_proc_U0_ap_ready) and (ap_sync_ready = ap_const_logic_0))) then 
                Block_proc_U0_ap_ready_count <= std_logic_vector(unsigned(Block_proc_U0_ap_ready_count) + unsigned(ap_const_lv2_1));
            end if; 
        end if;
    end process;

    warpTransform_U0_ap_ready_count_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_sync_ready = ap_const_logic_1) and (warpTransform_U0_ap_ready = ap_const_logic_0))) then 
                warpTransform_U0_ap_ready_count <= std_logic_vector(unsigned(warpTransform_U0_ap_ready_count) - unsigned(ap_const_lv2_1));
            elsif (((warpTransform_U0_ap_ready = ap_const_logic_1) and (ap_sync_ready = ap_const_logic_0))) then 
                warpTransform_U0_ap_ready_count <= std_logic_vector(unsigned(warpTransform_U0_ap_ready_count) + unsigned(ap_const_lv2_1));
            end if; 
        end if;
    end process;
    AXIvideo2xfMat_U0_ap_continue <= ap_const_logic_1;
    AXIvideo2xfMat_U0_ap_start <= ((ap_sync_reg_AXIvideo2xfMat_U0_ap_ready xor ap_const_logic_1) and ap_start);
    AXIvideo2xfMat_U0_start_full_n <= ap_const_logic_1;
    AXIvideo2xfMat_U0_start_write <= ap_const_logic_0;
    Block_proc_U0_ap_continue <= ap_const_logic_1;
    Block_proc_U0_ap_start <= ((ap_sync_reg_Block_proc_U0_ap_ready xor ap_const_logic_1) and ap_start);
    Block_proc_U0_start_full_n <= ap_const_logic_1;
    Block_proc_U0_start_write <= ap_const_logic_0;
    R_address0 <= warpTransform_U0_P_matrix_address0;
    R_address1 <= ap_const_lv4_0;
    R_ce0 <= warpTransform_U0_P_matrix_ce0;
    R_ce1 <= ap_const_logic_0;
    R_d0 <= ap_const_lv32_0;
    R_d1 <= ap_const_lv32_0;
    R_we0 <= ap_const_logic_0;
    R_we1 <= ap_const_logic_0;
    ap_done <= xfMat2AXIvideo_U0_ap_done;
    ap_idle <= (xfMat2AXIvideo_U0_ap_idle and warpTransform_U0_ap_idle and Block_proc_U0_ap_idle and AXIvideo2xfMat_U0_ap_idle);
    ap_ready <= ap_sync_ready;

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    ap_sync_AXIvideo2xfMat_U0_ap_ready <= (ap_sync_reg_AXIvideo2xfMat_U0_ap_ready or AXIvideo2xfMat_U0_ap_ready);
    ap_sync_Block_proc_U0_ap_ready <= (ap_sync_reg_Block_proc_U0_ap_ready or Block_proc_U0_ap_ready);
    ap_sync_continue <= ap_const_logic_1;
    ap_sync_done <= xfMat2AXIvideo_U0_ap_done;
    ap_sync_ready <= (ap_sync_warpTransform_U0_ap_ready and ap_sync_Block_proc_U0_ap_ready and ap_sync_AXIvideo2xfMat_U0_ap_ready);
    ap_sync_warpTransform_U0_ap_ready <= (warpTransform_U0_ap_ready or ap_sync_reg_warpTransform_U0_ap_ready);
    p_dst_TDATA <= xfMat2AXIvideo_U0_p_dst_TDATA;
    p_dst_TDEST <= xfMat2AXIvideo_U0_p_dst_TDEST;
    p_dst_TID <= xfMat2AXIvideo_U0_p_dst_TID;
    p_dst_TKEEP <= xfMat2AXIvideo_U0_p_dst_TKEEP;
    p_dst_TLAST <= xfMat2AXIvideo_U0_p_dst_TLAST;
    p_dst_TSTRB <= xfMat2AXIvideo_U0_p_dst_TSTRB;
    p_dst_TUSER <= xfMat2AXIvideo_U0_p_dst_TUSER;
    p_dst_TVALID <= xfMat2AXIvideo_U0_p_dst_TVALID;
    p_src_TREADY <= AXIvideo2xfMat_U0_p_src_TREADY;
    start_for_xfMat2AXIvideo_U0_din <= (0=>ap_const_logic_1, others=>'-');
    warpTransform_U0_ap_continue <= ap_const_logic_1;
    warpTransform_U0_ap_start <= ((ap_sync_reg_warpTransform_U0_ap_ready xor ap_const_logic_1) and ap_start);
    xfMat2AXIvideo_U0_ap_continue <= ap_const_logic_1;
    xfMat2AXIvideo_U0_ap_start <= start_for_xfMat2AXIvideo_U0_empty_n;
    xfMat2AXIvideo_U0_start_full_n <= ap_const_logic_1;
    xfMat2AXIvideo_U0_start_write <= ap_const_logic_0;
end behav;
